### ISSUE TITLE
Quick access Panel: doesn't show the Tone Equalizer Graph

### ISSUE THREAD

**Issue by Leanndruss** [darktable-org/darktable#10894]
**Describe the bug/issue**

In the Quick access Panel I've added the Tone Equalizer Graph widget but it doesn't appear.
I think that it is a bug and the grapht doesnt have enough height because a line appears

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'Manage module layouts'
2. Click on 'quick access' --> "+" --> All Available modules --> Tone equalizer graph
3. See the quick access panel and it doesn't appear

**Expected behavior**

**Screenshots**
![imagen](https://user-images.githubusercontent.com/78982102/149587615-cd9fcaec-937a-48a4-ac8c-7b54f8ab1c57.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.9.0~git90.d26580fbb5-1
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by dterrahe** [comment]
Makes sense; within the tone equalizer module, the graph doesn't have an explicit size set. It just expands to the minimum allocated space in the advanced tab, which is determined by the number of sliders in the other two tabs. In the QAP where it is on its own, there is no minimum space. So we need to request a minimum size for the graph, but not so much that it creates empty space in the other two tabs. So it needs to be font size dependent. And change when the font size is changed in settings.

Or it might be possible to do this with a css rule that only applies if the graph is  shown within QAP? What do you think @Nilvus ? I suppose you would need a `gtk_widget_set_name` so you can refer to the graph from css?

**Comment by Nilvus** [comment]
@dterrahe: I check and this can't be fixed by CSS. There's no specific about graph here, just basics widget. If I set one, this will affect all other things placed in quick access panel. So probably something else to do with Gtk/C code. I ping @AlicVB as he works on that part.

**Comment by dterrahe** [comment]
> There's no specific about graph here, just basics widget.

I know. That's why I asked:

> I suppose you would need a `gtk_widget_set_name` so you can refer to the graph from css?

Then you would be able to refer to it by name. Would that then work? Or would you also have a problem distinguishing if it is in the QAP at the moment? Would that also need a name set or wouldn't it work anyway?

I know you say you don't know anything about C, but this stuff on the gui side is not that hard and it sometimes feels like you could be much more efficient if you were involved on both sides or at least had a somewhat better understanding so miscommunications happen less often...

**Comment by Nilvus** [comment]
> > There's no specific about graph here, just basics widget.
> 
> I know. That's why I asked:
> 
> > I suppose you would need a `gtk_widget_set_name` so you can refer to the graph from css?
> 
> Then you would be able to refer to it by name. Would that then work? Or would you also have a problem distinguishing if it is in the QAP at the moment? Would that also need a name set or wouldn't it work anyway?

Oups, sorry, I read your comment probably too quickly. With a name, this should work but to be sure, It would be good to test with a PR your propose so (or if it's just a line to add, I could test on my side If you post here which line to add in which file and line.

> I know you say you don't know anything about C, but this stuff on the gui side is not that hard and it sometimes feels like you could be much more efficient if you were involved on both sides or at least had a somewhat better understanding so miscommunications happen less often...

I understand that but this need time to be involved more on both sides. And here, sorry again, I understand now that I should have read better your comment... and it's because I try to work on some things waiting since quite some days quickly. And here, badly...

**Comment by AlicVB** [comment]
For me, this issue should be fixed widget by widget, as they probably won't need the same size...

Not sure if that can be set by css, but as I know your are a magician in this area, just add something like `gtk_widget_set_name(GTK_WIDGET(g->area), "blabla");` in toneequal.c after line 3195 and you'll be able to play :)

**Comment by dterrahe** [comment]
> this issue should be fixed widget by widget

Most other graphs explicitly set their size; either square or resizeable via ctrl-scroll.

tone equalizer is different, because it is in a separate tab and the other tabs normally define its size. You don't want to make it smaller, because that would just leave empty space, and there's also no need to make it larger, since 9 sliders and a toggle in the first tab should force more than enough space. But that doesn't apply in QAP. Implementing full ctrl-scroll resizing for just qap is overkill imho and would then also have to be aware of whether the slider is in the module or QAP (and respond to switching groups, which would be a whole load of hassle. Fixing it in CSS, if possible, would be much nicer. But it would have to be conditional on this widget being within the QAP list (not just everywhere), so the QAP group might also need a name and the CSS rule would have to refer to both. Not sure if possible. @Nilvus is the expert.

**Comment by Nilvus** [comment]
Adding line suggested by AlicVB is ok to have an id for graph in basics panel but unfortunately, no CSS fix work. I try to use a huge (and a reasonable too) min-height and even working with padding/margin but nothing works. Gtk Inspector Tool confirm that settings are applied to the widget but nothing change, the bug remains.

There's probably something more needed. About what you said @dterrahe, I agree this need to be applied only in that specific graph and setting only to this with CSS (if we suppose CSS could work here) is possible as any widget/box used to set QAP have some "basics..." id. See Gtk Inspector Tool below:

![image](https://user-images.githubusercontent.com/45535283/150580277-435e4d16-35b2-4140-a2b2-f8d6634ea4b1.png)

So if we want to apply a CSS setting to just the graph in QAP, CSS will begin with:

#basics-widget #toneeqgraph

And, as you can see, I set a huge min-height to the graph but nothing happen. That means, there's probably something else to update in Gtk code.

**Comment by dterrahe** [comment]
Ah yeah, forgot; a drawing area widget doesn't read its own size from css. We may need to wrap it in a box and label that; hopefully that will work. Then the _action_ also needs to point to the box. Which in this case might not cause any problems, since the widget doesn't support shortcuts anyway (the action is just there to allow putting it in QAP).
