### ISSUE TITLE
Improve star rating filter

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11757]
A couple of issues with the new star rating filter in the top bar of the lighttable view.

The first is that, in its default (all selected) state, it draws the eye a bit too much and can be distracting - it's quite bright and high-contrast.

The second is that it is somewhat hard to read at-a-glance. If I select a range of ratings, especially in the middle of the range, I have to look hard to see which stars I've selected. For example:

![Screenshot_2022-05-07_22-49-21](https://user-images.githubusercontent.com/9555491/167272781-2e11f15d-b4fb-414c-9f1f-4414c905bf3d.png)

The main thing I see when I just glance at this control is that two stars are highlighted. But I have to engage extra brain functions to work out which two stars are selected (is it two to three, or four to five?). In the previous interface, I usually used "greater than or equal to" by default so when I saw two stars highlighted in the top bar I instantly knew what that meant without having to think further (two == two or more stars). It's "intuitive" in the way that looking at an analogue clock is. In the new way it's the opposite, in that if I select "two or more stars", I will actually see three stars highlighted. This is hard on my tiny brain.

**Comment by AxelG-DE** [comment]
I maybe get blamed again, but I don't see the need  of range selection and have the very same problem than @elstoc
I also mostly worked with = >= and sometimes <=
This combined with the chosen stars next to it is close to the mathematical writing.

In principle, this is the function I really want to have back, as I don't see how to better integrate it in current solution.

Switchable / configurable is here maybe also not optimal

**Comment by Nilvus** [comment]
@AxelG-DE: please help us to make progress. We understood that you don't like that. It's the fourth time you write it. I know kids scream from what they want until they have it, not adults. Sorry to be hard but it's annoying.

Said that, yes, it's normal to have issues on new huge changes. About those stars, I completely understand your statement @elstoc.

Let me explain first differences between old and new system:

On old system, to choose which stars to select, you need to:

1. click on menu
2. select stars line wanted
3. if wanted to change mathematical condition, so click on menu of it
4. then select condition

On new system now:

1. click or click-and-drag to select wanted stars

Just quicker.

Now that it is explained, the issues. I agree that it is quite bright by default. I made that and be sure I try to find the better compromise I can. I first tried less brighter but your other issue here (knowing which stars are selected) was just worst.
That was really hard to find how to have not too bright way but good contrasted one to see which stars are selected and which are not.

But seems that, even if it's hard to make it worst, it's not the good way.

Reading your issue and thinking about it, I'm wondering if it would just be better and simpler to not have "highlighted" part and just have stars filled for selected ones (and increase filled contrast).

What do you think of that proposal?

I could test actually on CSS but I fear this would also need some Gtk update (as I remember highlighted CSS setting is the same for all widgets). About Gtk update, I can't do something until some days (I only have my pro computer and can't install a Git dev on it ; until my personal computer go back from repair center).

**Comment by AxelG-DE** [comment]
> Sorry to be hard but it's annoying

It is also annoying how a valid request gets ignored so thoroughly

**Comment by Nilvus** [comment]
> It is also annoying how a valid request gets ignored so thoroughly

Just stating that you don't like it do not make it valid. It would also have been better to post an issue with what you don't understand or things to improve (like this issue). Also better to avoid posting in issues, even if they were related to filters, they were not related to that filter. Also taking care of what is better with new system (and what is bad like what is explain correctly here) regarding old system, will also help to find a better way. I could understand that the new way need improvement but I also still think that the old way too. So more constructive to find how to have the better of both world. I'm quite sure we could find it.
Your reactions for that do not help a second in that direction.

**Comment by elstoc** [comment]
> I know kids scream from what they want until they have it, not adults.

Calling people childish is not necessary here.

> Just stating that you don't like it do not make it valid.

Sometimes reversion _is_ the solution and "I don't like it" is the only valid comment that can be made. Just asserting that we need to "improve" the existing solution does not make that the right approach either. I still much prefer the simplicity of the old method even if it took a few extra clicks to do things or an additional filter to select a range. Range selection is a very niche and uncommon thing to need and honestly I can't think of a use case for it.

> So more constructive to find how to have the better of both world. I'm quite sure we could find it.

Maybe. I'm sceptical at the moment whether both of my requests in this issue can be satisfactorily resolved without reversion.

> I'm wondering if it would just be better and simpler to not have "highlighted" part and just have stars filled for selected ones (and increase filled contrast).

It might half-resolve the issue here. But the easy-readability is as much of a problem for me and I'm not sure how simple that is to resolve.

**Comment by AxelG-DE** [comment]
Let us stop arguing here! I actually like that the team of dt devs and contributors is a bunch of nice chaps and we should preserve that!

I have two proposals to improve current situation
#1 might get accepted, might not 
#2 is controversial, but please allow me to speak that out and it is meant in a constructive manner!

1) I suggest to put some more space between the rejected and the 0-starred icon and yet double that space between the rest of the 1-5 stars (sorrry no ability and time atm to make a mokup, let me illustrate with X = rejected, 0=zero stars and § to be considered star and _ is the space, then it can look like: x_0__§§§§§ (we can further think to have the middle star "3" a tiny bit separated or lifted few pixels, -motivated by the haptical thing on 5 at the num-pad)

2) @Nilvus, @AlicVB:  don't hit me right away, leave me 2Min headway :-) (this might be not the final proposal but a start)
can we keep the today's usability (click and drag on the today's star icons) and have the "old" look just as an additional gauge (admittedly will be hard to make it clear it is an illustrator only) next to it. Don't scream right away, give it two seconds. (This gauge can be switched on and off via settings). I admit, for range it will not be too easy, but I think doable.

**Comment by Nilvus** [comment]
Ok, I was quite harsh but so many harsh messages I read since yesterday.

Of course, sometimes reversion is the solution. Here, I find the new way better than the old one. As you said, it's the joy of development, we can't please anybody. So what is the solution? Having more clicks, I don't like that. I understand that you could prefer the simplicity of the old version as I prefer the simplicity of new one. Not easy.

I often go back to all images except rejected to only rejected one or select images with four stars or five stars (or both). Sometimes less than those. it's really quicker with the new way (quite less clicks).

> Maybe. I'm sceptical at the moment whether both of my requests in this issue can be satisfactorily resolved without reversion.

I hope we can anyway find a way to please all views.

For that, I propose to try (put those lines in CSS textview) if that could improve (or not) readability:

```
@define-color range_sel_color transparent;
@define-color range_icon_color white;
```

It's just for test and even those lines are not perfect as they impact all widgets selections (so selections on other will just be not visible). It's to check what that could change if there's no highlight on stars filters and only filled stars. Even that is not perfect. I would see more filled stars but will be not only CSS here to improve that.

**Comment by Nilvus** [comment]
>     1. I suggest to put some more space between the rejected and the 0-starred icon and yet double that space between the rest of the 1-5 stars (sorrry no ability and time atm to make a mokup, let me illustrate with X = rejected, 0=zero stars and § to be considered star and _ is the space, then it can look like: x_0__§§§§§ (we can further think to have the middle star "3" a tiny bit separated or lifted few pixels, -motivated by the haptical thing on 5 at the num-pad)
> 
>     2. @Nilvus, @AlicVB:  don't hit me right away, leave me 2Min headway :-) (this might be not the final proposal but a start)
>        can we keep the today's usability (click and drag on the today's star icons) and have the "old" look just as an additional gauge (admittedly will be hard to make it clear it is an illustrator only) next to it. Don't scream right away, give it two seconds. (This gauge can be switched on and off via settings). I admit, for range it will not be too easy, but I think doable.

I really love your answer here. Thanks and sorry for being harsh. Harsh messages yesterday just make me really sad.

About your proposal, I like them, especially first one. For second one, I'm just not sure to understood it correctly.

**Comment by elstoc** [comment]
Let's just all try to remember that things get heated because we all want darktable to be the best it can be, and sometimes that is hard.

**Comment by elstoc** [comment]
>  I suggest to put some more space between the rejected and the 0-starred icon and yet double that space between the rest of the 1-5 stars

Putting the two reject/0 icons on their own would definitely help readability.

**Comment by parafin** [comment]
Current way is definitely not readable or intuitive, and the reason is that same star icons in the row are used very differently elsewhere (old filters and image overlay). There number of lit stars is the rating, and their position in the row doesn’t really matter. In the modern filters position matters, and it means that user has to count it, which is much harder than just counting the number of objects. My suggestion would be to change this filter appearance to differ from image overlay. E.g. put 1x, 2x, 3x, etc. inside the star, or render five star rating as five stars in the square, not one star in fifth position.

**Comment by AlicVB** [comment]
@elstoc : please correct me if I'm wrong, but if I understand correctly, one of your main concern (apart from colors) is that you can't know in one sight which are the selected values, right ?
I mean, when you have 3-4 selection, it's hard to know directly (without involving some sort of icon counting) those "numbers", right again ?

If that's it, I perfectly understand your concern, and that's clearly a regression here... I will try to come with some proposals asap

**Comment by elstoc** [comment]
@AlicVB that is indeed my primary concern, as also illustrated by @parafin's comment. 

I will say, though, that I'm also sceptical about the range selection widget as a concept. When it comes to UI, I much prefer sticking to generally-accepted design patterns as these will be more familiar to new users, who already have enough trouble working out how to do image processing.

**Comment by AxelG-DE** [comment]
May I add one more comment in regards to refinement...

What @parafin said with his last sentence is perfectly the trouble, at the same time I understand, light up more stars is needed for the range (e.g. 2-4 stars)...

[A]
Here comes my proposal:
1) if one selects =3star than light 1st to 3rd star (like you do today for 1-3stars)
2) of one selects 1-3 stars, also fill the three stars but no background highlight **and** underline, (maybe even with arrows at that line) the 1-3stars

[B]
Alternatively, turn my proposal around:
1) select =3star gets star 1-3 lit no background highlight
2) select 1-3 stars, like today's situation
Admittedly that might look confusing, but maybe we are getting there....

[C]
3rd alternative is a kind mix between the two [B1 + A2]:
1) select =3star gets star 1-3 lit no background highlight
2) if one selects 1-3 stars, also fill the three stars but no background highlight **and** underline, (maybe even with arrows at that line) the 1-3stars

Plus my above proposed separation... :-)

I know there will be "buts"....

**Comment by elstoc** [comment]
@AxelG-DE this sounds more confusing to me. I think someone probably needs to mock up some proposals visually so we can understand the options better.

**Comment by AlicVB** [comment]
here is a first draft... (done very quickly in gimp, so take it just as mockup to be refined) : 
![Capture d’écran_2022-05-08_11-43-37](https://user-images.githubusercontent.com/1818223/167292412-80035118-0931-4377-bf8f-f1f36b527d85.png)
1. first line is actual situation for reference
2. second line, we use numbers. that should be easier to read on first sight. You can see that I have kept the 2 first icons as they are self explanatory imho, and more important, that allow to know what the filter is for, esp with the first star.
3. third line, we use the "dice" representation of the numbers. Should be quite easy to read too, based on the fact that it's the first abstract representation used with kids, at least in France...

imho, n°2 is the best (with some tweaking on the color, we should emphasis more the selected number compared to the others) What worried me a little (not sure) is that users may not understand directly that it's the "rating filter", even with the first crossed star...

I find n°3 a little bit messy... representations are hard to distinguish... I've tried with "just" point instead of the reduced stars... but then if we accept to loose the "star" icons, it's better to go with number....

**Comment by elstoc** [comment]
I agree, the second is best of the three options, though without the "zero star" icon it would be hard to know what is being represented. Unfortunately consistency would suggest that the zero star should have a number 0 against it. A label at the start (or even a star icon) would perhaps help (so it goes `*x01234` if you take my meaning) though this might mess up the look of it.

**Comment by Jiyone** [comment]
I agree the second is best.

**Comment by AxelG-DE** [comment]
atm I also think No2 is good to read. 
still think my Idea(s) might bring us a step more foward.

I try to do a mock-up maybe tomorrow or so, I am just very poor in gimp :-(

**Comment by Nilvus** [comment]
> I agree, the second is best of the three options, though without the "zero star" icon it would be hard to know what is being represented. Unfortunately consistency would suggest that the zero star should have a number 0 against it. A label at the start (or even a star icon) would perhaps help (so it goes `*x012345` if you take my meaning, where the * is essentially a label) though this might mess up the look of it.

It's the best but that point is important. I fear that do not have stars will be worst to understand what is it. As @parafin suggest, maybe we could text numbers inside stars (making icons a little bigger, it's possible regarding padding we can see outside them).

I think it should be good to test those numbers inside actual stars to be sure rendering is correct.

And @AxelG-DE idea to add a little space between reject and no star icons and another one between no star icons and five one is also good I think.

**Comment by elstoc** [comment]
> I fear that do not have stars will be worst to understand what is it.

Sure. That's why I suggested a star icon as a label

**Comment by AlicVB** [comment]
hmm... an icon as a label would be great... but I fear that a star like we have actually would put confusion... @Nilvus : I'm sure you are able to design a "filter by rating" icon :) don't you ? (isn't that an elegant way to delegate something we are not able to do ? :D)

For the icon + number, why not, I have planed to do that as a third mockup, but I just have failed to get something readable... either the star what to prominent, either the number... but now that I think to that again, I've not tested the star as a background...

@AxelG-DE : Yes, if you can achieve a mockup that would be great, as I'm not sure to understand everything in your idea? For instance, as @elstoc that seems quite confusing, but I have the feeling that what you have in mind doesn't correspond to your original idea...

**Comment by Nilvus** [comment]
> hmm... an icon as a label would be great... but I fear that a star like we have actually would put confusion... @Nilvus : I'm sure you are able to design a "filter by rating" icon :) don't you ? (isn't that an elegant way to delegate something we are not able to do ? :D)

hmm, I fear that this will increase icons/size of the widget but if we have many people for that, i could try. When my computer will be back!

> For the icon + number, why not, I have planed to do that as a third mockup, but I just have failed to get something readable... either the star what to prominent, either the number... but now that I think to that again, I've not tested the star as a background...

I would give a try before adding an icon as a label!

**Comment by AlicVB** [comment]
here is a very rough try for the version (see last line)... I fear that the star are hard to distinguish... but that would also be the case for the other proposals !
![Capture d’écran_2022-05-08_11-43-37](https://user-images.githubusercontent.com/1818223/167309266-3b0374cc-9d6f-4aee-88fa-ea8f1f662f21.png)

**Comment by AxelG-DE** [comment]
With regards to my proposals [A], [B] and [C] above, here I try to illustrate, what I meant. 
I am fine to further get it fine-tuned...

I realized, even once I did a little with gimp, but this evening I was not able to do the least things, hence I used KolourPaint. Sorry for ugly look :blush: 

This is my mock-up proposal for =3*
![grafik](https://user-images.githubusercontent.com/49004103/167310237-2601b22c-a6ac-49c5-9450-4955f46b2c18.png)

And this is a mock-up proposal as an example for range 2-4star
![grafik](https://user-images.githubusercontent.com/49004103/167310411-53c90553-57ab-4819-b120-85dceafedcb7.png)
(I would give that "arrow" into the group, where user can give it the different color, like Jiyone did for his sliders in light orange)

**Comment by aurelienpierre** [comment]
The previous way of showing stars was both legible and functional. 

This design forces us to chose one or the other.

This is a regression.

Now we are discussing how to make it less bad, not better.

This is a fucking nightmare.

Please revert.

**Comment by elstoc** [comment]
I know it's not constructive and I'm not going to get sweary and angry, but I do agree that we've still not got something that's better than what's in 3.8.1.

**Comment by Nilvus** [comment]
> The previous way of showing stars was both legible and functional.
> 
> This design forces us to chose one or the other.

Yes, it's an issue but this design also allow to do selections with 1 click instead of 2 or 4 on previous one, depending on changes.

> This is a regression.

So revert will also be a regression.

> Now we are discussing how to make it less bad, not better.

That doesn't mean, it can't be better.

> This is a fucking nightmare.

As always, exaggerated... We talk about an UI, not the end of the world...

**Comment by elstoc** [comment]
> Yes, it's an issue but this design also allow to do selections with 1 click instead of 2 or 4 on previous one

The question is: have we gained more than we've lost? At the moment I don't think we have.

**Comment by AlicVB** [comment]
I'll try to let the swearwords apart (even if it's hard) and explain again why I (and others) do think this is better : 
- previously each change need at least 2 click. often 3 (to switch between >= and =)
- what is proposed needs only 1 click or 1 click+drag.
- previously to see quickly what happen you have to look in 2 places : the operator (>= or =) and the stars. personally I've many time overlooked the operator, or confused >= and = (quite similar for my eyes)
- what is proposed is better regarding the operator (maybe we should improve the color, though) but still need some work on the other part... and that's exactly what we are trying here.
- previous implementation doesn't allow real range which correspond to usecases : for example show all "not so great" images (1-3)...
- previously, the implementation use a very strange widgets stacking involving some overlay and such, which needed some exceptions in the code and break lot of theming (colors, alignments, margins, tooltips)
- what is proposed take way less horizontal space, which is now quite a critical thing for the top bar
- what is proposed is more consistent with what we have for the other filters (well that's an easy one, the author is the same :))

Note that most points have already been explained in the mentioned PR.



> The question is: have we gained more than we've lost? At the moment I don't think we have.

I think so... and that's here where we disagree... That's not a problem, we just need to find altogether how either to improve my widget, either how to improve the previous one... (and you can see that the issues in both cases are not so different)

**Comment by Nilvus** [comment]
sorry, just a mistake

**Comment by aurelienpierre** [comment]
> previously each change need at least 2 click. often 3 (to switch between >= and =)

So make it a combobox of operators ?

> what is proposed needs only 1 click or 1 click+drag.

Except if you want to reset filters, now it's right-click -> contextual menu -> click.

> previous implementation doesn't allow real range which correspond to usecases : for example show all "not so great" images (1-3)...

Which was a feature requested by whom ? The culling process is usually a gradual up-rating process where you give one more star at each step until you find yourself happy with a selection of pictures to edit. This only needs > or >=.

> what is proposed take way less horizontal space, which is now quite a critical thing for the top bar

It takes less horizontal space because it also takes much more vertical space, so overall real-estate consumption increased

![Screenshot_20220508_231943](https://user-images.githubusercontent.com/2779157/167316255-26410374-0dd2-40ce-bb66-7483b5bc3658.png)

**Comment by AxelG-DE** [comment]
I also try to go away from ranting and keep clean language. I try to be constructive, hence please do not let us forget my above [mock-up](https://github.com/darktable-org/darktable/issues/11757#issuecomment-1120466989).


>     * previously each change need at least 2 click. often 3 (to switch between >= and =)
> 
>     * what is proposed needs only 1 click or 1 click+drag.

I see that, I admit that, just honestly, I did not have any single issue with that, as the gain was a very very clean UI, where I ever new, where I am. And I am sensitive for extra-clicks

I notice one thing: @aurelienpierre is ever sensitive for vertical UI space 
![grafik](https://user-images.githubusercontent.com/49004103/167356018-7ef310e0-6780-476c-b9a0-4d49096c1e78.png)


Where I am more worried about the bar on top of collections (I even donno yet, how AP made it not to have the  color-selectoin there, but I'll find):
![grafik](https://user-images.githubusercontent.com/49004103/167356292-85a01aa0-7fe6-4579-a4ec-3f3cf5760f8f.png)

**Comment by AxelG-DE** [comment]
> I'll try to let the swearwords apart (even if it's hard) and explain again why I (and others) do think this is better :

I think with beginning of this issue, we started to cool down a bit already. The hot temper involved is a sign, we all love dt. I also had my deep frustrations the other days on another end...

I am very sensitive for useless additional clicks, fun fact, here I was not so bothered...

So I am not arguing, just try to mention my opinion

>     * previously each change need at least 2 click. often 3 (to switch between >= and =)

Was o.k.-ish for me as I usually stood on "=" and just changed the stars

>     * what is proposed needs only 1 click or 1 click+drag.

Correct and maybe appreciated one day. Just atm:
- it is not so obvious, where the triangle to open a combobox is known for long time
-  it can(!) give additional bother, when it does not react as expected (happens for me sometimes and i have to re-do, just hard to reproduce)

>     * previously to see quickly what happen you have to look in 2 places : the operator (>= or =) and the stars. personally I've many time overlooked the operator, or confused >= and = (quite similar for my eyes)
>
>     * what is proposed is better regarding the operator (maybe we should improve the color, though) but still need some work on the other part... and that's exactly what we are trying here.

- matter of taste :-)
- but I think, with my above [mock-up](https://github.com/darktable-org/darktable/issues/11757#issuecomment-1120466989) (which indeed will have to be refined). we couuld have the operator next to it as illustration and I would be already very fine

>     * previous implementation doesn't allow real range which correspond to usecases : for example show all "not so great" images (1-3)...

- here I really ask, whether this is a use case for minority or majority.
- I did this just by <=3, where rejectets where not shown

 
>     * what is proposed take way less horizontal space, which is now quite a critical thing for the top bar

- in the first place all widgets where "on" and then it was actually much more space, which triggered me. Just today I learned, they can be off
- I do llike the icon for sorting way better than the old one: ![grafik](https://user-images.githubusercontent.com/49004103/167360135-adb9beae-6f5c-42d5-9654-47d457a63976.png)
- particularly when sorting is decending, it looked confusing

> Note that most points have already been explained in the mentioned PR.

Me as the master testing pilot :laughing: was offline for one year for hose renovation (and still busy with the final touches), so you would have had a harder time by then. Now it is now :-) :-)


> > The question is: have we gained more than we've lost? At the moment I don't think we have.
> 
> I think so... and that's here where we disagree... That's not a problem, we just need to find altogether how either to improve my widget, either how to improve the previous one... (and you can see that the issues in both cases are not so different)

I like this attitude a lot!
I see, both sides need to improve the communication and I see a clear trend to that and I will also work hard on it
- (A) should use clean language and be respectful
- (B) hopefully uses more rational arguments then "is better now" or "was lots of work". That is emotionally very understandable but less rationally, IMHO

**Comment by AxelG-DE** [comment]
Ammendment:

I noticed one difficulty with the dragging function.
Often I click already, before the mouse came to a full stop, than this is already considered as a "drag" and causes me inadvertant results.

Additional question:
can we have this combo-thing from "sort-by" next to stars also instead of right click?
![grafik](https://user-images.githubusercontent.com/49004103/167362532-ea4431f5-ad53-455d-b61f-cfd8ef5d6b63.png)
And offer there the = selection too, not only the ranges (clicking today on 3* makes it 3*-> max)

**Comment by aurelienpierre** [comment]
And I just discovered that one click over a star selects pictures with exactly that rating. Which is not what I need. Previous design allowed me to select pictures > some rating in just one operation.

This is another **objective** regression. It's not about liking it or not, it's about having to spend more time and more steps to achieve the same task. 

The proposed solution fails.

**Comment by AlicVB** [comment]
> Except if you want to reset filters, now it's right-click -> contextual menu -> click.

or double-click like most widgets in dt ;) (yes, that can be seen as an hidden feature, but well... that's every where in dt atm)


> This is another **objective** regression. It's not about liking it or not, it's about having to spend more time and more steps to achieve the same task.

I'm not sure to understand completely. I suppose that the right-click is harder with your graphic tablet than the left-click ? (sadly I don't own that equipment...) In that case, maybe the solution proposed by @AxelG-DE would solve that (I'm not a big fan, but...)


> can we have this combo-thing from "sort-by" next to stars also instead of right click?
> ![grafik](https://user-images.githubusercontent.com/49004103/167362532-ea4431f5-ad53-455d-b61f-cfd8ef5d6b63.png)



> And offer there the = selection too, not only the ranges (clicking today on 3* makes it 3*-> max)

That's very easy, and we should also enhance the text for the >= entries

**Comment by TurboGit** [comment]
For 4.0 we need to make progress, so here is what I propose (and correct me if I missed a point in this large and convoluted discussion):

1. Change GUI to use numbers instead of stars (2nd proposal from @AlicVB)
2. Add an arrow on the right of the star to make it clear that there is a sub-menu

@AxelG-DE :
> And offer there the = selection too, not only the ranges (clicking today on 3* makes it 3*-> max)

For this you just click on start 3 and you have only 3. That's the "=" you are speaking about, right?

Then we will have another full release circle to enhance those new widgets and the collection filter.

**Comment by AxelG-DE** [comment]
I am not happy with the numbers tho, AFAIK @AlicVB also not, and come back again to my [mock-up](https://github.com/darktable-org/darktable/issues/11757#issuecomment-1120466989)

Also I am still in particular not happy, if I click 3* or 4* in the "=" mode, just one star is actually lit (in its 3rd or 4th position in that given example)

> For this you just click on start 3 and you have only 3. That's the "=" you are speaking about, right?

@TurboGit you are right and you may consider it a dupe, however I find it confusing, that in the sub-menu kind of only have >= choice, where "=" is the vast majority in my "wokflow"

**Comment by TurboGit** [comment]
> that in the sub-menu kind of only have >= choice, where "=" is the vast majority in my "wokflow"

That's where the problem is. I have always use `>=` and this is the default operator in 3.8.1 IIRRC.

**Comment by AlicVB** [comment]
> I am not happy with the numbers tho, AFAIK @AlicVB also not, and come back again to my [mock-up](https://github.com/darktable-org/darktable/issues/11757#issuecomment-1120466989)

hmm... that's certainly my bad english, but in fact the mockup n°2 is my preferred one :)

About your mockup, I like the separation between the 2 first icons and the numbers (maybe a with little less space) but I find the arrow and the coloring of your proposal really confusing and hard to read, especially once you downscale the mockup to the "real" size they will have in the ui (well, at least in my non-dpi screen) More important, I'm not convinced at all that this can solve the issue mentioned by @elstoc and @parafin ...

**Comment by AxelG-DE** [comment]
@AlicVB 
ohhhh please ignore that red ring on my screenshots, that came from the sofware I used....

**Comment by AlicVB** [comment]
no pb... I've guess that ;). My bad, when I speak about the colors, I mean how you change the colors of the stars and their background to reflect the settings...

**Comment by elstoc** [comment]
I'm sorry but I still don't think we're anywhere with this. Is the size of this change the main reason not to revert? I'm not necessarily saying abandon altogether but it (the new widgets in general) feels like it's some way from release-ready and we're approaching feature freeze.

**Comment by paperdigits** [comment]
If I may chime in a bit late, I'd agree that this is really hard to use. I've tried for about 20 minutes and I still can't seem to make a selection properly. I don't find this easy to use at all and my desire would be to revert the GUI pieces to what they are in the current 3.8.1

**Comment by MStraeten** [comment]
perhaps let's take a look at the functional and non-functional requirements that the implemented solution should fulfill. just picking out some aspects won't be helpful.
if there's an consensus on these requirements then there's a base to discuss the implemented solution. Or just accept the implemented solution as a first step to a nit yet defined target if it matches the requirements.

Unfortunately a cople of weeks before code freeze isn't the best time for requirements elicitation ;)

**Comment by aurelienpierre** [comment]
Let us recall that @phweyland proposed an elegantly simple solution to achieve the same purpose back in february 2022.

The feature being discussed here is a technical debt in search of a problem to solve. It is riddeled with bugs in addition of degrading usability. 

What is really stupid here is that there is already a draft PR to rewrite it and merge it with usual collections because that's merely a UI redundancy. So all that bug fixing and doc writing for something that is already planned for deprecation is beyond idiotic.

Highjacking the dev due-process under the pretext that feature-freeze is there is another fallacy. We have every right to decide to postpone a release, we made that rule, we can revise it anytime, there is no external pressure to release anything on 21th june. On the other hand, once it's released, there is no turning back.

And I don't care that it took 3 months to produce this nightmare. @phweyland 's work was overwritten without a second thought, so that argument is voided by the very persons using it now.

This feature needs a revert now. It's a regression and an insult to intelligence.

Ultimately, I don't really care anymore. I have my fork now and 5500 subscribers who will be made aware of what I think dt is headed to. Destroy dt all you want, I have backups.

**Comment by elstoc** [comment]
This doesn't resolve the issues I've raised here but puts off their resolution until a later date and gives the option to temporarily reinstate the old widget.

**Comment by TurboGit** [comment]
@elstoc : As this is a quite convoluted issue, do you think you could create a new one with the fix still to be done and let this closed for good?

**Comment by elstoc** [comment]
I'm not sure that's necessary. The issues are still as I explained in the first post and the comments are a discussion of the options (I guess you just want to hide the frustrated/angry comments?). I still don't know what the resolution should be to these issues and someone would have to review this discussion again to get a full understanding (or we'd have to repeat half the comments in the new issue).

I could copy-paste my first post to a new issue if you really want but I'm not sure what that achieves.

**Comment by AxelG-DE** [comment]
Maybe I don't get it, but I am a bit surprised, #11801 didn't include some of the changes discussed here, where I thought they where widely accepted, like the separation space between rejected/not rated and the 1*-5* as well as the sub-menu indicator and operators.

...if then range rating could highlight the amount of stars selected (e.g. =3* should lid 3 stars, sorry for being repetitive, but English is my second language), I could make my peace with it :)

**Comment by AlicVB** [comment]
yes, my bad. There's good and valuable ideas/material here... among other less constructive msg...
My only fear is that all this will be hard to handle again here... but let's see... Ultimately, if that fail, I'll try to compile the ideas and screenshorts here in a new issue, but I would prefer not ;)

**Comment by TurboGit** [comment]
@AxelG-DE : The idea behind #11801 is to recover only the old star rating to get the same filter has it was on 3.8.1 and let time to discuss more and compile all the new ideas into a workable UI. For the later we need some time and it will be for the next release cycle. Sure we will get there at some point.

**Comment by AlicVB** [comment]
ok, so I've started to look at that for real.
The main point where we all agree seems to add spaces between the 2 first icons and the others. Right ?
Considering how the code has been done (esp. the "snap" and rounding operations) it's not so easy... What I can propose for 4.0, is this : 
![Capture d’écran_2022-05-15_21-09-14](https://user-images.githubusercontent.com/1818223/168491790-b5157a3c-8794-4eea-9698-9984cc285688.png)
or this : 
![Capture d’écran_2022-05-15_22-30-44](https://user-images.githubusercontent.com/1818223/168492679-80bd02aa-271d-415a-a5c4-e27bdbaf6fad.png)

I find the space a little too big on the first screenshot, and almost not noticeable on the second, but I can't go below the space of 1 icon without a lot of changes in the code... (This changes can and will happen for 4.2, but it's not realistic for 4.0... esp. considering that we have a fallback now.)

So the question is : What do you prefer here for 4.0 ?
- the actual UI with no space
- the above UI with too big space
- the above UI with very small space

**Comment by elstoc** [comment]
I know this will not be popular but my opinion is that for 4.0 we should do the following:

1. Amend the top bar so that it has the old ratings filter and the new color labels filter by default
2. Hide the collection filters module from the UI so that top bar options cannot be changed (I'm assuming that can be done without killing the top-bar functionality).

This shouldn't be a massive update to the code and will allow for breathing space to get it right for 4.2. As it is I think we're pushing a half-finished feature and we should wait until it's feature-complete and has a polished UI.

**Comment by paperdigits** [comment]
I agree with Chris. I don't think this is ready for 4.0.

I still can't wrap my mind around why the top bar is linked to this module. It is just such a strange design decision.

**Comment by TurboGit** [comment]
Well for me the new collection filter is an improvement and we certainly want to make it visible to users. With a simple pref we can get old UI, but for me this should not be the default. We already have some feedback saying that this new module is nice, so let's move forward and see how good or bad this will be received. Again, with latest version everyone should be happy and I'm always in favor of moving forward.

**Comment by elstoc** [comment]
> Again, with latest version everyone should be happy

Well perhaps I _should_ be happy...

**Comment by TurboGit** [comment]
Well I cannot force you to be happy :) But at least you can work around any itches you have with new UI.

**Comment by AxelG-DE** [comment]
> - the above UI with too big space

Just focus on this one question: the upper one with "too big space"

**Comment by Nilvus** [comment]
Thanks @quovadit. This seems just a good and simple idea actually to improve that. I hope that this will help and goes in good direction. Your tooltip proposal is really clearer than actual one I think. I hope I will not be the only one to agree with that.

**Comment by aurelienpierre** [comment]
> Well I cannot force you to be happy :) But at least you can work around any itches you have with new UI.

@TurboGit you will be happy too with bugs piling up against a stack of bloatware replacing 400 lines of code with:

``` 
 src/common/collection.c                  |  1207 +--
 src/common/collection.h                  |    88 +-
 src/libs/filtering.c                     |  2049 ++++++
 src/libs/filters/aperture.c              |   118 +
 src/libs/filters/colors.c                |   429 ++
 src/libs/filters/date.c                  |   126 +
 src/libs/filters/exposure.c              |   142 +
 src/libs/filters/filename.c              |   466 ++
 src/libs/filters/focal.c                 |   118 +
 src/libs/filters/grouping.c              |   193 +
 src/libs/filters/history.c               |   177 +
 src/libs/filters/iso.c                   |   143 +
 src/libs/filters/local_copy.c            |   166 +
 src/libs/filters/module_order.c          |   185 +
 src/libs/filters/rating.c                |   286 +
 src/libs/filters/rating_legacy.c         |   243 +
 src/libs/filters/ratio.c                 |   172 +
 src/libs/filters/search.c                |   206 +
 src/libs/tools/filter.c                  |   745 +-
 src/libs/tools/global_toolbox.c          |    99 +-
```

Not to mention that quick filters used to be a view and collections the real filters, but now everything is a filter under different names. Way to keep dt simple and understandable. 

Welcome in geektable, the SQL GUI.

**Comment by MStraeten** [comment]
DAM is all about SQL GUI.
One important motivation for the effort invested in implementing a scene referred workflow in darkroom was to get options the old display referred tools didn’t give.
Nonetheless - there are plenty users around using that old display referred stuff just because that’s ‚intuitive‘ to them (or better, they don’t want to change their learned habits)

That’s exactly the same in the discussion of DAM Features in lighttable: Now there are two ways to work with collections and features. And it’s up to the user to decide which way to go. Following old habits ore the new. And no habit is worse than the other.

so keep in mind one strength of darktable: giving options to users even it’s hard to find a proper way to cope with all that options by selecting a subset…

**Comment by aurelienpierre** [comment]
> One important motivation for the effort invested in implementing a scene referred workflow in darkroom was to get options the old display referred tools didn’t give.

No, not at all. Scene-referred has never been about (more) options, it's only about allowing to edit HDR without the typical color saturation mess-up that comes with HDR in display-referred. This problem has zero solution in display-referred space.

Color work is a full-time job and color is a complicated matter taught over 5 years at university. 

File management is something we do and practice since the dawn of GUI. It shouldn't have to be reinvented and relearned in 2022. It's the fundamentals of computer using. We have design guidelines for that matter, specifically to unify the process across apps and OSes.

Or you are saying that we also should go 5 years to university to get a degree in professional file management to be able to use darktable ?

**Comment by MStraeten** [comment]
I'm able to use all that scene referred stuff even without having got an university degree on color science, so i'm pretty sure that no university degree is needed to use file management ;)

**Comment by elstoc** [comment]
As has already been discussed, the tooltip is a workaround to these issues but my understanding is that these widgets are designed to be easy-read as well as easy-write and IMO that has not yet been done. I don't think this should have been closed.

**Comment by AlicVB** [comment]
I wouldn't even call that a workaround, more an "easy to do before release" enhancement. For the request in itself, it will be for 4.2 (hoping we can find a consensus)

**Comment by emko** [comment]
had to revert to old mode, this new star rating just makes me have to think about what its doing every time i look at it and most of the time i have to hover to read the tool tip, basic tool like selecting what stars to filter by should not make you have to think 

clicking fifth star only highlights the fifth star? super confusing 
clicking the slashed star i would think removes the star filter? no its for not rate???
have to select all the items to see all image? 

was this made to troll users? 

i can't see how you can improve this ? when there are many real world example of functional implementation of filtering by stars done for years this is not one of them.

**Comment by elstoc** [comment]
Also see the related issue https://github.com/darktable-org/darktable/issues/11887

**Comment by quovadit** [comment]
having used the new star rating filter for a while, I still love dragging to select any wanted range.

But it's really very hard to read:

- '>= 2' shows 4 stars
- '>= 4' shows 2 stars

I don't think that there is any design that could fix this issue, as long as we stick with the stars.

So although it's not really beautiful, I would love to have numbers instead of the 5 stars.

I would also add the drop-down arrow to open the menu without rightclick.

Here's a mockup:
![image](https://user-images.githubusercontent.com/5677563/193470604-7635deaf-92e5-4bf8-82fa-9ec0ff44468b.png)

**Comment by quovadit** [comment]
the functionality is great, I can easily select 2-3 stars, only 1 star,  or >=3 stars.
switching between =1 and >=3 is quite inconvenient with legacy, and 2-3 is not possible at all.

So for me it's just a matter of showing what's selected, and using numbers would solve this.

**Comment by elstoc** [comment]
For consistency, the star with a slash through it should say "0", but then there's no indication that it's a ratings widget. TBH, though, all of the other range widgets have the same problem.

**Comment by quovadit** [comment]
Yes, 0 would be consistent, you could even argue to use -1 instead of the X.
But I think the mockup is a great compromise, because it's always clear whats selected, AND you know that it's about stars.

**Comment by elstoc** [comment]
As I say, I still prefer, and will continue to use the legacy widget

**Comment by TurboGit** [comment]
@phweyland : You may want to give your view on this!

**Comment by Nilvus** [comment]
Reopen it that way is also debatable. With a title like improve, all things can be improved, again and again. I disagree with you and especially because your comment doesn't add anything useful for improving it more. I'm always surprised by some of your reactions regarding that filter. You're usually really helpful and constructive and I love that. But for that filter...
Letting that opened would not help too to filter what is fixed or improved and what could remains.

I think and hope that what I've changed improve readibility. Maybe, there's a way to find even better but regarding changes made, a new issue would be better to start from new changes. It would even be better to open a new one after some field testing and with constructive comment not just things against that filter comment and revert back ones like i read.

Some users have reported to find that widget easier and faster than old ones. Others have found it harder to read. Being on a side or the other, regarding feedback I read, seems clearly depends on the eyes of the user. And it's hard for me as with my eyes, readibility was already clear and good on first UI. And topbar do not allow huge place.

**Comment by dterrahe** [comment]
> Some users have reported to find that widget easier and faster than old ones. Others have found it harder to read.

The old one is still available (I'm happily using it) so I also feel that the perceived problems with the new one may be getting too much attention. Imho the biggest mistake was to not keep the old one as default.

**Comment by Nilvus** [comment]
Thanks @dterrahe. You're probably right. I do not made or even propose that choice and as topbar filter could be changed, i understand that keeping old widget by default would have been better. That remains possible. If needed, even if I prefer the new one, I understand that and could support change default one set.

**Comment by elstoc** [comment]
There were two issues here. The first (and least important to me) was the high contrast, which is now better than it was thanks to the latest PR. The second (and most important for me) is the fact that when you glance at it with 3-4 stars are selected it looks very similar to when 2-3 stars are selected and I dislike the extra cognitive effort required to distinguish between them. I still don't believe that this issue is resolved.

> Imho the biggest mistake was to not keep the old one as default

Agreed, first thing I did when I upgraded was to put the old one back.

**Comment by dterrahe** [comment]
We have a very conservative user base who don't like change/challenges to their (eye) muscle memory and that is fair enough. On the other hand there are a lot of devs who want to introduce improvements. Wherever we can easily support them alongside existing functionality, even if only for a transition period, we should. This gives a new approach the time to ripen. And _if_ we decide the old way can be removed, we can first make the new one the default, getting even more eyes on it. But forcing everyone over immediately without an urgent need is asking for trouble (which was received, in this case, unfortunately and not completely deservedly).

Of course the _reason_ we like to force change on people is that we very much believe that it is all _better_ and we don't want to deprive anyone of more happiness. But the hurry really isn't there; just put everything in the release notes and those who love the new and shiny will find it.

Flip-side; if we do support duplicated functionality for a while, we should also come back to it and clean it up if there are no real reasons to keep it anymore (except for pure inertia). Otherwise our maintenance nightmare just grows. Maybe we should have a section in release notes "scheduled for removal" to give anyone a chance to come up with good reasons they can't move with the times yet (and also to later be able to say we warned them).

**Comment by AllergicMushroom** [comment]
Greetings everyone. The following paragraph is a quick introduction of myself, so you can jump to the next if you're not interested. My name is Luis, and I have a background in Mathematical Optimization and Software Development. I got into photography two years ago and remained casual until a few weeks ago. Recently, I've started exploring bird photography, and I've started editing photographies. That along with my passion for open source software brought me to darktable, and I hope I can contribute to this beautiful project.

Now onto the issues. From what I understand, the remaining problem is the readability difference between selecting two different ranges, e.g., 2 to 3 stars or 3 to 4 stars. I don't use this feature myself, but I do agree with @elstoc . To improve this, I suggest making stars different depending on their value. For instance, there could be a number inside the stars (1 to 5), or each star could have only X "arms" (X from 1 to 5), i.e., only top arm, top and upper right arm, top, upper right and bottom right arms, etc.

**Comment by TurboGit** [comment]
@AllergicMushroom : Welcome Luis. Just a note that we are in a "release mode" at the moment, so do not expect too much a discussion on new features during this period.

**Comment by AllergicMushroom** [comment]
So where are we on this? Is there a related PR, or can I try sketching out a solution?

**Comment by AxelG-DE** [comment]
@AllergicMushroom over the time there was a config possible to not show this range selector anymore but the former filter thingie.

<img width="822" height="91" alt="Image" src="https://github.com/user-attachments/assets/00bd903a-e037-4f9d-9d96-391329b99884" />

Then the originator and me got shut up :-) 

numbers inside the stars was a discussion but somebody was against it for the sake of cleanness. A star with only one arm might look odd but maybe the rest of the arms are dimmed? 

I am neither Pascal nor a dev, but anyhow, I could imagine a sketch might be welcome. Maybe start with some mockups first and put them in a WIP issue or such
