### ISSUE TITLE
macOS System Shortcuts Do Not Work

### ISSUE THREAD

**Issue by glacials** [darktable-org/darktable#15475]
### Describe the bug

On macOS, ⌘ A, ⌘ C, ⌘ X, and ⌘ V are system-wide shortcuts for select-all, copy, cut, and paste, respectively. In darktable, they do not work; you must use Ctrl-A, Ctrl-C, Ctrl-X, and Ctrl-V instead.

### Steps to reproduce

1. Run darktable on macOS.
2. Focus a text box, like the filter text box in lighttable.
3. Type some letters, like `asdf`.
4. Press ⌘ A ⌘ X.

Nothing happens.

### Expected behavior

All the text is selected and then deleted, and populates the clipboard.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

macOS Sonoma 14.0

### Describe your system?

MacBook Pro 13-inch, M1, 2020

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by parafin** [comment]
Related to #4384

**Comment by dterrahe** [comment]
The code in `_mods_fix_primary` is intended to address this issue for MacOS users. It was introduced a long time ago but I don't recall if I ever received the feedback I requested a few times.

https://github.com/darktable-org/darktable/pull/8078#issuecomment-782615034

I was under the impression that this worked nowadays, since I also can't recall the last time I saw a complaint about this.

Since I don't have access to a mac myself, I'm totally reliant on macos users and developers to support this and fix possible regressions (in dt, gtk and/or the OS). There's little more that I can do besides putting some code in that according to the docs should do what you want, throwing it over the wall and shouting _please test this_ **and** _provide feedback_.

Confusingly, this issue lists the OS both as linux and Sonoma. I would not be surprised when running linux on apple hardware, that gtk doesn't suggest the ctrl -> cmd substitution. _But I have no way of knowing besides reading the complaints_.

Oh, after writing all that, I realise this is about _text box_ shortcuts. i.e. default gtk or system ones. On linux and windows, those "just work"; the gtk Entry widget takes care of them and the darktable shortcuts system sees that they are already dealt with and ignores them. No idea what might be required on MacOs to enable them...

Again, would be useful to know if this has always been the case, was a regression caused by #8078 or was a newer regression (by dt/gtk/os).

**Comment by zisoft** [comment]
> Run darktable on macOS.
Focus a text box, like the filter text box in lighttable.
Type some letters, like asdf.
Press ⌘ A ⌘ X.

Cannot reproduce that on my Intel MacBook Pro 16 (2019), running Sonoma 14.0
⌘A, ⌘X, ⌘C, ⌘V -- all work as expected. Tested with several text boxes in lighttable.

**Comment by apfelkraut** [comment]
This was fixed for the homebrew-based build with https://github.com/darktable-org/darktable/pull/14660. I suppose it was not taken over to the official macports-based build?

**Comment by zisoft** [comment]
It seems that MacPorts gtk ([file list](https://build.macports.org/builders/ports-14_x86_64-builder/builds/1015/steps/install-port/logs/files)) does not contain `gtk-keys.css` for the Mac theme.

@MStraeten: Can you please verify on your build system if this file/path exists:

`/opt/local/share/themes/Mac/gtk-3.0/gtk-keys.css`

**Comment by MStraeten** [comment]
it exists

**Comment by MStraeten** [comment]
seems   `<data>${prefix}/share/themes/Mac/gtk-3.0/gtk-keys.css</data>` needs to be added to darktable.bundle.
please confirm with this build [darktable-4.5.0+997~g0321f1b325_arm64.dmg](https://mega.nz/file/fb4DwIyC#eYnjaVCKD85y8yklSq1ZG1N95kC9hRgfXv-j4l4zFqo)
but: rename your `~/.config/darktable` directory first to avoid messing up your 4.4.2 database

**Comment by glacials** [comment]
@MStraeten I can confirm the 4.5.0+997 linked build resolves the issue! The version in Homebrew (4.4.2) still experienced the issue, and the version I was using before was the arm64 bundle linked from [this page](https://www.darktable.org/install/), which experienced the issue as well.
