### ISSUE TITLE
Darktable hangs on activating raw cacorrect

### ISSUE THREAD

**Issue by sh1llo** [darktable-org/darktable#15600]
### Describe the bug

Activating Raw Chromatic Aberattion module causes to Darktable rendering thread to freeze. 

### Steps to reproduce

1) Import raw from https://discuss.pixls.us/t/thundery-summer-sunset-and-a-question-poll/34696 forum thread and switch to dark room mode.
2) Activate Raw Chromatic Aberration
3) 'Working...' will be shown over the image and will stay stuck. DT may still stay responsive if there is another thread in the pool, but pressing 'D' (to go back to Lighttable) will freeze it.

Afterwards, kill -9 will be necessary.
On restart, thumbnail generation also hangs (with DT responsive) and you can salvage by Discard History on the thumbnail, followed by Alt-F4 and another kill -9.
Starting with empty ~/.config/darktable did NOT help.
I did not notice high CPU usage and I couldn't find the hung thread with gdb, unfortunately.
I've been seeing the problem on master for months - I have a large archive of old edits with Raw Chromatic Aberration module active and they were getting nuked as soon as I clicked on them - but due to the nature of the issue, I couldn't pinpoint the module that was causing it.

### Where did you install darktable from?

darktable.org

### darktable version

master, problem replicable for the last several months

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 20.04

### Describe your system?

Using x11, DT compiled with clang-12.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

GTX 1080, nvidia-driver-520

**Comment by jenshannoschwalm** [comment]
Can't reproduce here on latest master, neithere with the mentioned image nor any else.

To test and get further
1. Please share one of those mentioned images plus the xmp - maybe there is something else
2. please start from a terminal as `darktable -d pipe` and share the output.

**Comment by sh1llo** [comment]
The image is from the linked thread; direct link: https://discuss.pixls.us/uploads/short-url/kK9WQWYX0DZaovF9uWkN6N1oxLu.ARW


```
~ > ~/local/darktable-dist/bin/darktable -d pipe
darktable 4.5.0+1118~ge78edab35e-dirty
Copyright (C) 2012-2023 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> DISABLED - API version NOT AVAILABLE  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> DISABLED - Compressed LUTs NOT supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> DISABLED
  libheif                -> DISABLED
  libjxl                 -> DISABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     6.3513 dt_dev_pixelpipe_synch_all [full]                                  defaults 0.0485s, history 0.0343s
     6.3514 pixelpipe_cache_checkmem   [full]                                  64 lines (important=0, used=0). Freed 0MB. Using using 0MB, limit=501MB
     6.3514 pixelpipe starting CL      [full]                                  (   0/   0) 1247x 830 scale=0.2537 --> (   0/   0) 1247x 830 scale=0.2537 device=0 (nvidiacudanvidiageforcegtx1080)
     6.3631 modify roi IN              [full]           demosaic               (   0/   0) 4916x3276 scale=1.0000 --> (   0/   0) 1247x 830 scale=0.2537 
     6.3631 modify roi IN              [full]           rawprepare             (   0/   0) 4928x3276 scale=1.0000 --> (   0/   0) 4916x3276 scale=1.0000 
     6.3631 pixelpipe data: full       [full]                                  (   0/   0) 4928x3276 scale=1.0000 --> (   0/   0) 4928x3276 scale=1.0000 
     6.3663 pixelpipe process CL       [full]           rawprepare             (   0/   0) 4928x3276 scale=1.0000 --> (   0/   0) 4916x3276 scale=1.0000 IOP_CS_RAW
     6.3693 pixelpipe process CL       [full]           temperature            (   0/   0) 4916x3276 scale=1.0000 --> (   0/   0) 4916x3276 scale=1.0000 IOP_CS_RAW
     6.3724 pixelpipe process CL       [full]           highlights             (   0/   0) 4916x3276 scale=1.0000 --> (   0/   0) 4916x3276 scale=1.0000 IOP_CS_RAW
     6.4359 pixelpipe process CPU      [full]           cacorrect              (   0/   0) 4916x3276 scale=1.0000 --> (   0/   0) 4916x3276 scale=1.0000 IOP_CS_RAW
     6.4624 [cacorrect] blockdenom vanishes
     6.4624 [cacorrect] blockdenom vanishes
```


Github complains about unsupported file type on trying to upload the xmp, so pasting it here (save as DSC01629.ARW.xmp):

```
<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:darktable="http://darktable.sf.net/"
   exif:DateTimeOriginal="2023:01:12 19:54:00.000"
   xmp:Rating="1"
   xmpMM:DerivedFrom="DSC01629.ARW"
   darktable:import_timestamp="63834823376751448"
   darktable:change_timestamp="63835058181825769"
   darktable:print_timestamp="-1"
   darktable:xmp_version="5"
   darktable:raw_params="0"
   darktable:auto_presets_applied="1"
   darktable:history_end="12"
   darktable:iop_order_version="2"
   darktable:history_auto_hash="51b4c8dfaf0343b6b8a4426d25c72fa0"
   darktable:history_current_hash="24f5e28839d2d187c1bad93e0102251c">
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq>
     <rdf:li
      darktable:num="0"
      darktable:operation="rawprepare"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="00000000000000000c000000000000000002000200020002003c000000000000"
      darktable:multi_name=""
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz12eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfOqC/0AAogFpBh0E"/>
     <rdf:li
      darktable:num="1"
      darktable:operation="demosaic"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="0000000000000000000000000500000001000000cdcc4c3e"
      darktable:multi_name=""
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz12eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfOqC/0AAogFpBh0E"/>
     <rdf:li
      darktable:num="2"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="7"
      darktable:params="gz48eJzjZhgFowABWAbaAaNgwAEAOQAAEA=="
      darktable:multi_name=""
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz12eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfOqC/0AAogFpBh0E"/>
     <rdf:li
      darktable:num="3"
      darktable:operation="colorout"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="gz35eJxjZBgFo4CBAQAEEAAC"
      darktable:multi_name=""
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz12eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfOqC/0AAogFpBh0E"/>
     <rdf:li
      darktable:num="4"
      darktable:operation="gamma"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="0000000000000000"
      darktable:multi_name=""
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz12eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfOqC/0AAogFpBh0E"/>
     <rdf:li
      darktable:num="5"
      darktable:operation="temperature"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="ea8934400000803f8460ad3f0000807f"
      darktable:multi_name=""
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz12eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfOqC/0AAogFpBh0E"/>
     <rdf:li
      darktable:num="6"
      darktable:operation="channelmixerrgb"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="gz04eJxjYGiwZ8AAxIqRD5igmAWIGYHY4/oWO5tlu+3Ov5ziCrKLESoPALRkCYY="
      darktable:multi_name="scene-referred default"
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz09eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi48L/AcCEA0AmawnoA=="/>
     <rdf:li
      darktable:num="7"
      darktable:operation="exposure"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="00000000000080b93333333f00004842000080c001000000"
      darktable:multi_name="scene-referred default"
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz09eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi48L/AcCEA0AmawnoA=="/>
     <rdf:li
      darktable:num="8"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="gz02eJybNXOy49kzXw60vp7owAAGDkD6hBMEQ8AsoBr9ZRU2IDG1yHQHruvKQHaDPUz+7BkfO2YgzQLEjFAxRiQ2DDBBaQC8LhQY"
      darktable:multi_name="scene-referred default"
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz09eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi48L/AcCEA0AmawnoA=="/>
     <rdf:li
      darktable:num="9"
      darktable:operation="flip"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffffffff"
      darktable:multi_name="auto"
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz12eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfOqC/0AAogFpBh0E"/>
     <rdf:li
      darktable:num="10"
      darktable:operation="highlights"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="010000000000803f00000000000000000000803f0000c04000000000cdcc4c3d0000655126560000108d479300000000"
      darktable:multi_name="default"
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz11eJxjYGBgYARiCQYYOOHEgAYY0QVwggZ7CB6pfOqC/0AAogFkph0B"/>
     <rdf:li
      darktable:num="11"
      darktable:operation="cacorrect"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="0000000002000000"
      darktable:multi_name=""
      darktable:multi_name_hand_edited="0"
      darktable:multi_priority="0"
      darktable:blendop_version="13"
      darktable:blendop_params="gz12eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfOqC/0AAogFpBh0E"/>
    </rdf:Seq>
   </darktable:history>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
```

I suspect this could be a multithreading issue. I'm running on 5900x (12 cores, 24 threads), so testing on a CPU with lots of cores may be more likely to freeze.
I managed to turn on the CA twice without the immediate freeze, which is how I have the minimalist xmp; normally kill -9 prevents saving it. Importing with this xmp immediately froze DT.

**Comment by sh1llo** [comment]
Addendum: on a hunch, I tried earlier versions (with clean db) and found that the bug first appears at f8bad8a64b and does NOT appear at 4fd9560fc6.
f8bad8a64b is 'Merge pull request #15056 from ralfbrown/cacorrect_opt cacorrect: performance optimization'

**Comment by jenshannoschwalm** [comment]
Maybe a clang problem with our code? Could you try compiling with gcc?

**Comment by TurboGit** [comment]
@ralfbrown : Can you have a look at this one?

@sh1llo : Can you tell us which compiler and which options have you used? TIA.

Maybe a similar issue to the one fixed in fd9c6e86c9a247fad328df0f65596432f97549f5?

**Comment by sh1llo** [comment]
@jenshannoschwalm gcc, not easily. I'm on Ubuntu 20.04 and the only reason I use clang is that it's easier to get the compatible version.
@TurboGit clang-12 and clang++-12, no special options for cmake.

**Comment by jenshannoschwalm** [comment]
L. 888 - 891 looks wrong as we run that code inside 

```
#ifdef _OPENMP
#pragma omp single
#endif
{
  ...
  #ifdef _OPENMP
  #pragma omp parallel for schedule(static)
            // collapse(2) doesn't help here, likely due to cacheline bouncing
  #endif
   .......
}
```

**Comment by sh1llo** [comment]
Tested @jenshannoschwalm's patch, and unfortunately it didn't seem to solve the problem.

**Comment by jenshannoschwalm** [comment]
Could you check with -t 1 please?

**Comment by sh1llo** [comment]
With darktable -t 1, raw cacorrect works, no patch needed.

**Comment by sh1llo** [comment]
Putting #undef _OPENMP at line 1210 does not fix the freeze, but putting it at line 741 does. Note that these two lines are right after omp barriers, so I can't easily nail it down any further.

**Comment by TurboGit** [comment]
> but putting it at line 741 does

@ralfbrown : Something weird to me, on this line we have `#pragma omp single` but inside this block we have `#pragma omp parallel for schedule(static)` which makes no sense to me as this is a mono thread block (right?)... Maybe an issue while refactoring the code?

**Comment by sh1llo** [comment]
@TurboGit Note that @jenshannoschwalm's patch already removes that pragma, but that didn't help (at least not on its own).

**Comment by jenshannoschwalm** [comment]
What i don't understand is, i don't have any issues here at all. 16 threads intel. Fedora 38. gcc.
Maybe you have a OpenMP mismatch for clang?

@MStraeten may i ping you here as a daily clang user?

**Comment by sh1llo** [comment]
I just tested darktable --disable-opencl, and it works fine with the modules I commonly use (but disabled cacorrect), so if there's a general problem with OpenMP, it'd have to have an oddly specific effect.

**Comment by ralfbrown** [comment]
> > but putting it at line 741 does
> 
> @ralfbrown : Something weird to me, on this line we have `#pragma omp single` but inside this block we have `#pragma omp parallel for schedule(static)` which makes no sense to me as this is a mono thread block (right?)... Maybe an issue while refactoring the code?

AIUI, when you have a "single" inside a parallel, only one thread enters the section and the rest wait until that thread leaves it.  A nested "parallel" would then be able fire up multiple threads with the one thread that entered the "single" as the controlling thread; when that block finishes (all threads done), the one thread from the "single" block continues until it finishes the "single", at which time the threads from the enclosing "parallel" can resume and run the code after the "single" block in parallel.  Whew....

**Comment by TurboGit** [comment]
> AIUI, when you have a "single" inside a parallel,

No, here we have a "parallel" inside the "single".

**Comment by ralfbrown** [comment]
Yes, and the single thread can spawn multiple others.  OpenMP has provisions for handling multiple "teams" of threads, though I don't recall the details.

**Comment by TurboGit** [comment]
> Yes, and the single thread can spawn multiple others. OpenMP has provisions for handling multiple "teams" of threads, though I don't recall the details.

I see, didn't know that. Thanks.

**Comment by kmilos** [comment]
It is also possible to get [Clang 13 on Ubuntu 20.04 by enabling the proposed archive](https://launchpad.net/ubuntu/+source/llvm-toolchain-13).

Can you also test w/ that version perhaps?

**Comment by sh1llo** [comment]
... I'll see what I can do. I eventually plan to upgrade to 22.04, anyway, and presumably the problem goes away then.

However, it's possible that this is not a compiler bug but a code bug that depends on the compiler, and if so, it'd be really helpful to understand the problem before looking for the workarounds. I'd like to try to at least narrow down the crashing point while I can still easily reproduce it.

**Comment by jenshannoschwalm** [comment]
I think i spotted an issue ...

**Comment by sh1llo** [comment]
@jenshannoschwalm I've tested the pr, and it solves all my issues. Thank you!
