### ISSUE TITLE
5.2.1 Crashes on startup

### ISSUE THREAD

**Issue by efrederi** [darktable-org/darktable#19308]
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

Installed latest version 5.2.1. from darktable website on W11. Running it first time gives splash screen, last message 'Initializing LUA' and then nothing, sort of. Application remains active, icon still on taskbar, and when clicking it two small windows flash up and disappear. That is it. lock files are still there (and will be removed when DT is killed).

OpenCL seems ok, and also starting without openCL gives same behaviour. 

### Steps to reproduce

1. Download
2. Install
3. Run
4. 

### Expected behavior

Darktable should start normally

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

5.2.1

### What OS are you using?

Windows

### What is the version of your OS?

windows 11 pro (10.0.22631 Build 22631)

### Describe your system

Intel I7-10700, Nvidia RTX 4060

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

 Nvidia RTX 4060

**Comment by efrederi** [comment]
Snippet from log:
4.8121 [sql] C:/msys64/home/bill/src/darktable-5.2.1/src/libs/tools/timeline.c:673, function _block_get_at_zoom(): prepare "SELECT db.datetime_taken AS dt, col.imgid FROM main.images AS db LEFT JOIN memory.collected_images AS col ON db.id=col.imgid WHERE dt > 0 ORDER BY dt ASC"
     4.8144 [lighttable] expose took 0.0000 sec
     4.8325 [lighttable] expose took 0.0000 sec
     4.8799 [dt_get_system_gui_ppd] system ppd is 1.000000
     4.8799 [screen resolution] setting the screen resolution to 168.000000 dpi 
     4.8859 [lighttable] expose took 0.0000 sec
     4.8968 [lighttable] expose took 0.0000 sec
     4.9145 [lighttable] expose took 0.0000 sec
     5.0974 [lighttable] expose took 0.0000 sec
     5.1157 [lighttable] expose took 0.0000 sec
     5.1962 [lighttable] expose took 0.0000 sec
     5.2132 [lighttable] expose took 0.0000 sec
     5.2298 [lighttable] expose took 0.0000 sec
     5.2375 [sql] C:/msys64/home/bill/src/darktable-5.2.1/src/libs/lib.c:730, function dt_lib_init_presets(): prepare "DELETE FROM data.presets WHERE operation=?1"
     5.2377 [sql] C:/msys64/home/bill/src/darktable-5.2.1/src/libs/lib.c:822, function dt_lib_init_presets(): prepare "SELECT name FROM data.presets WHERE operation=?1 AND op_version=?2 ORDER BY writeprotect DESC, name, rowid"
     5.2378 [undo] clear list for 2047 (length 0)
     5.2378 [undo] clear list for 2047 (length 0)
     5.4648 [lighttable] expose took 0.0000 sec
     5.4721 [undo] clear list for 2047 (length 0)
     5.4721 [undo] clear list for 2047 (length 0)
     5.6147 LUA ERROR : cannot open C:\Users\erwin\AppData\Local\darktable\luarc: No such file or directory
     5.7067 [dt_get_system_gui_ppd] system ppd is 1.000000
     5.7067 [screen resolution] setting the screen resolution to 168.000000 dpi 
     5.7118 [lighttable] expose took 0.0000 sec
     5.7195 [lighttable] expose took 0.0000 sec
     5.7407 [lighttable] expose took 0.0000 sec
     5.7530 [lighttable] expose took 0.0000 sec
     5.9826 [camera_control] loaded 3 port drivers
     6.0056 [camera_control] 0 cameras connected
    32.6449 [dt_get_system_gui_ppd] system ppd is 1.000000
    32.6450 [screen resolution] setting the screen resolution to 168.000000 dpi 
    32.6508 [lighttable] expose took 0.0000 sec
    32.6754 [lighttable] expose took 0.0000 sec
    32.6932 [lighttable] expose took 0.0000 sec
    32.7111 [lighttable] expose took 0.0000 sec
    32.7290 [lighttable] expose took 0.0000 sec
    32.7495 [lighttable] expose took 0.0000 sec
    32.7703 [lighttable] expose took 0.0000 sec
    32.7953 [lighttable] expose took 0.0000 sec
    32.8089 [lighttable] expose took 0.0000 sec
    32.8345 [lighttable] expose took 0.0000 sec
   128.4515 [lighttable] expose took 0.0000 sec
   128.4681 [lighttable] expose took 0.0000 sec
   128.4845 [lighttable] expose took 0.0000 sec
   128.5017 [lighttable] expose took 0.0000 sec
   128.5185 [lighttable] expose took 0.0000 sec

At 128 I clicked icon in taskbar again cause two windows to flash and disappear again, as described.
Note also: Using setup with one 4K and one FullHD monitor.

**Comment by efrederi** [comment]
Set 4K monitor to fullHD and started DT and seems to work. Back to 4K and still starts. But unclear.

**Comment by Fredjikrang** [comment]
I have this same issue on PopOS with Nvidia drivers using the flatpak version. I had to disable GPU acceleration in order for Darktable to start.

**Where did you obtain darktable from?**

Pop Shop

**darktable version**

5.2.1 Flatpak

**What OS are you using?**

PopOS

**What is the version of your OS?**

Pop!_OS 22.04 LTS

**Describe your system**

AMD Ryzen 9 5900X, Nvidia RTX 3060 Ti

**Are you using OpenCL GPU in darktable?**

I was. I had to disable to run darktable.

**If yes, what is the GPU card and driver?**

Nvidia RTX 3060 Ti, tested with driver 570.172.08 and 575.64.05.

**Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip**

No response

**Comment by lucidillusions** [comment]
PopOS user, having the same issue as @Fredjikrang after updating to 5.2.1 from Pop Shop. 


**What is the version of your OS?**
Pop!_OS 22.04 LTS

**Describe your system**
Darktable Version: 5.2.1 (Flatpak)
GPU: NVIDIA GeForce GTX 1070
NVIDIA Driver Version: 570.172.08

**Are you using OpenCL GPU in darktable?**

No, Only way i can make it work: 

```
$ flatpak run org.darktable.Darktable --disable-opencl
     0.0001 [dt starting]
 darktable --disable-opencl
Gtk-Message: 16:54:33.920: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:54:33.921: Failed to load module "canberra-gtk-module"
```


Here is a list of all the steps we've taken to troubleshoot the issue:

> 1.     Confirmed gdb is installed on the host system via sudo apt install gdb.
> 2.     Confirmed libcanberra-gtk-module is installed on the host system.
> 3.     Installed the correct Flatpak SDK (org.gnome.Sdk/x86_64/48) and the debug extension (org.gnome.Sdk.Debug/x86_64/48).
> 4.     Used a GDB debug shell (flatpak run --command=sh --devel org.darktable.Darktable) to get a full backtrace. The backtrace showed a Segmentation fault in the _count_devices function within the ocl_icd_loader.c file, pointing to a crash during OpenCL initialization.
> 5.     Confirmed via flatpak list | grep nvidia that the correct NVIDIA Flatpak extension (org.freedesktop.Platform.GL.nvidia-570-172-08) is installed and matches the host driver version.
> 6.     Uninstalled and reinstalled Darktable with flatpak uninstall --delete-data followed by flatpak install, which did not resolve the issue.
> 7.     Attempted to find a way to disable OpenCL in the UI, but the options are grayed out and show as "not available."
> 8.     Confirmed that the application launches successfully when using the --disable-opencl command-line flag.

**Comment by gi-man** [comment]
@Fredjikrang and @lucidillusions Please start an issue in the flathub repo. The OP does not have an OpenCL issue.

https://github.com/flathub/org.darktable.Darktable/issues

**Comment by gi-man** [comment]
OP: Which monitor was setup as #1 (primary) on windows?

**Comment by Fredjikrang** [comment]
@gi-man I have added my issue to the flathub issue, but wanted to mention that it looks like my issue is not an OpenCL issue after all. I had to completely disable GPU acceleration in order to get Darktable to run.

Thank you for your assistance! If there is anything I can do to help please just let me know.

**Comment by Ruehrfisch** [comment]
I have a similar issue.
I updated darktable through two ways: manually and through Chocolatey on Windows. Both times, updated it from 5.0.1 to 5.2.1; when starting the newest version, I only get the shortest of display of the starting splash screen, and then nothing. The process however stays open and I need to kill it through the task manager.

**Comment by gi-man** [comment]
@Ruehrfisch Please start a new issue with all of the details of your system and ideally a -d common log file attached as a txt file.

**Comment by wpferguson** [comment]
Please add the -d lua flag too.  There was an issue causing a hang that was fixed by #19210   The fix is only available in master, but shows up in nightly and weekly builds.

**Comment by Ruehrfisch** [comment]
@gi-man @wpferguson 
I've got no idea what changed, but I don't experience the issue anymore. I just now had the time to install darktable 5.2.1 again using chocolatey (as usual), opened it with command line (which I usually don't) to get the -d common and -d lua log files. Now darktable starts without issue, also when starting it without command line.

**Comment by SilverGreen93** [comment]
I think I have the same problem described here. Windows 11, Darktable 5.2.1, on first launch after the computer is rebooted, the application just hangs after showing the splash screen. Further launches work fine, until the next system reboot.

**Comment by SilverGreen93** [comment]
I cannot reproduce it in 5.4.0. It might have got fixed.

**Comment by tomicp** [comment]
In 5.4.0. problem still exists. One solution I've found is to delete or rename luarc file...

**Comment by wpferguson** [comment]
The issue is fixed in master, though I don't know if it's been tested in a flatpak.  The fix will be available in 5.4.1 which should be out shortly.

**Comment by SilverGreen93** [comment]
Seems that for me it is fixed in version 5.4.1. Windows 11 25H2.
