### ISSUE TITLE
Darktable freeze on wayland

### ISSUE THREAD

**Issue by musicrizz** [darktable-org/darktable#19441]
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

i use ArchLinux with kernel 6.16.8-zen3-1-zen and Wayland enabled , AMD ryzen pro 7 .
The Darktable application freeze !!!
It is impossible to do import.
From collection already imported it freeze to open darkroom

### Steps to reproduce

Open darktable . you can do nothing because it is freeze

### Expected behavior

darktable shoud work !!

### Logfile | Screenshot | Screencast

darktable -v
darktable 5.2.1
Copyright (C) 2012-2025 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Exiv2                  -> 0.28.7
  Lensfun                -> 0.3.4
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.5.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  OSMGpsMap              -> ENABLED  - map view is available
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  LibRaw                 -> ENABLED  - Version 0.22.0-Devel202502
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

5.2.1

### What OS are you using?

Linux

### What is the version of your OS?

ArchLinux - 6.16.8-zen3-1-zen

### Describe your system

ArchLinux 
kernel : 6.16.8-zen3-1-zen
Wayland enabled

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD /ATI phoenix1

**Comment by gi-man** [comment]
Plase provide a txt file with the output from starting darktable using the -d common flag. This most likely has nothing to do with Wayland. Also, dt does not claim to work on wayland yet since there are still color management issues.

**Comment by wpferguson** [comment]
Please add the -d lua flag to see if the issue fixed by #19210.

**Comment by musicrizz** [comment]
Hi, I wanted to report the workaround I found.

My System: Lenovo P14s laptop with an AMD Ryzen 7 Pro, running Arch Linux with the GNOME desktop environment (kernel 6.16.8-zen3-1-zen).

The problem seems to be related to the OpenCL driver in Darktable. The application would freeze even when started with the --disable-opencl flag.

My first attempt at a workaround was to go to Settings -> Processing, uncheck "AMD ROCm", and check "RustiCL". 
However, the lightroom works, but the application would freeze again when I tried to import a file into the library (Import -> Add to Library).

I then found a more effective workaround: in the OpenCL driver settings, I unchecked all drivers. By doing this, the application works perfectly when launched with the --disable-opencl flag.

This entire problem appears to be Wayland / AMD specific. If I log into an X11 session (by disabling Wayland in /etc/gdm/custom.conf), the issue disappears completely, and Darktable works perfectly even with the default OpenCL settings enabled.

**Comment by schwoens** [comment]
I am having the same issue. Also Arch, also Gnome, also AMD. I tested both the flatpak and the native version (installed via pacman). The freeze does not seem to be connected to any particular action but occur randomly 5-30 seconds in.

Here is the output of `flatpak run org.darktable.Darktable -d common`: [darktable.log](https://github.com/user-attachments/files/22607135/darktable.log) not sure if this helps at all. All I did was opening the preferences. Then the application froze and I closed it.

The workaround mentioned above:

> I then found a more effective workaround: in the OpenCL driver settings, I unchecked all drivers. By doing this, the application works perfectly when launched with the --disable-opencl flag.

does not work for me. It seems to be an issue with XWayland as far as I can tell. The workaround that works for me is as follows:

1. Install the flatpak version of Darktable
2. Use Flatseal or similar program to give Darktable the permissions 'Wayland windowing system' (socket=wayland) and 'Fallback to X11 windowing system' (socket=fallback-X11)

As far as I understand Darktable seems to run on XWayland by default. Running `xlsclients` lists Darktable. After giving it the permissions above it does not get listed anymore so I assume it is running on Wayland directly now. I don't really understand why Darktable needs the Fallback permission to run on Wayland but it does not work without it.

Now running on Wayland I haven't had any freezes yet though I didn't test it extensively.

**Comment by gatecat** [comment]
I also have spotted a potentially-similar issue on Arch, Gnome (Mutter 49.0) and XWayland (24.1.8). 

The "freeze" is reproducible for me by switching away from Darktable and then back to it. It's not a total lockup however - tooltips still appear and it seems like it is still responding to clicks and keypresses, just not updating the window.

It doesn't freeze if I force the use of native Wayland rather than XWayland using `GDK_BACKEND=wayland`

**Comment by antage** [comment]
The same problem on Gnome 49 and Nvidia GPU.
`GDK_BACKEND=wayland` workaround works but I can't select any nested presets in modules.

**Comment by denclade** [comment]
I use Arch Linux (6.16.8, NVIDIA GPU). I have no problems with the Wayland version with OpenCL activated (NVIDIA CUDA). I can import without problems and nested menus work fine too. On the contrary, I had just switched to the native Wayland version because I was having problems with XWayland (Darktable sometimes didn't start at all or freezed after startup).

Maybe it has to do with the WM / Desktop Environment, I use Sway.

**Comment by mituzora** [comment]
FWIW, I can reproduce the issue using Gnome 49 and the wayland session.  I however CANNOT reproduce it using sway.  I'm running Arch Linux.  Using the GDK_BACKEND=wayland seems to resolve the issue. Normally I use sway, but my sway config has been messed up somewhere and causing a nasty memory leak or something.  I didn't seem to have issues before Gnome updated to 49, so I think there's a change in Gnome/GDM that causes this problem.

**Comment by gi-man** [comment]
I run fedora KDE using Wayland and don't have the issues listed above. I think the problem is the compositor instead of Wayland protocol.

**Comment by antage** [comment]
I had a hypothesis that the problem was caused by Gnome 49 disabling support for Xorg sessions. I recompiled `gdm`, `mutter`, `gnome-session`, and `gnome-shell` with support for Xorg sessions and tried to run Darktable in a Wayland session. The problem remained.

I also observe a similar problem in other applications running through `xwayland`.

I think this is a bug in `mutter` in the new version of gnome.

**Comment by garrett** [comment]
I'm seeing this too on Fedora 43 beta, which is GNOME 49 on Wayland. The **X11 session is no longer available in Fedora 43**, even as a post-install option; everyone must use Wayland now.

These bugs mean darktable will no longer work in Fedora or any other distribution that only uses Wayland, which also includes every distribution shipping GNOME 49 by default. It's not an isolated experience.

This happens with stable darktable (from Fedora) as well as the nightly builds (from OBS, running from a toolbox container).

Using darktable by default, it will randomly hang. Using `-d all` doesn't seem to show anything. Using `GDK_BACKEND=wayland` works mostly fine these days, except for the fact that nested menus instantly close instead of showing a submenu.

I've noticed that darktable only freezes when I have more than one display at the same time. (That is: "dualhead", 2 monitors.) If I turn off my secondary monitor and only have my main one on, then the X11 version running in XWayland seems to work fine without crashes.

Is everyone else here usually running with more than 1 display? What happens when you turn off all screens but your main screen?

---

Summary, as a table:

Environment | Displays | darktable Backend | Status
-- | -- | -- | --
Wayland | Multiple Monitors | X11 (XWayland) | ❌ Does not work: Application window randomly hangs/freezes.
Wayland  | Single or Multiple Monitors | Wayland native (`GDK_BACKEND=wayland`) | ⚠️ Almost works: Menus close when selecting sub-menus
Wayland  | Single Monitor | X11 (XWayland) | ✅ Works
X session | Any | X11 | ✅ Works

(Wayland is mandatory in Fedora 43, as well as for everyone who uses GNOME 49 on every distribution.)

**Comment by gi-man** [comment]
@garrett Fedora 42 KDE Wayland works fine for me.

**Comment by TurboGit** [comment]
For sure this is a big issue! We need a dev with GNOME 49 on Wayland to debug and fix this. At the moment I'm still using GNOME 48 on Debian. I hope Debian will ship GNOME 49 with X11 backend as an option to let me some time for fixing the issue.

@gi-man : Yes, as already reported this issue is maybe due to the mutter compositor which is not used in KDE.

**Comment by mituzora** [comment]
@garrett yes, I am running multiple screens, with my primary being a different size and refresh rate.  I am not at my editing machine, but I can verify if swapping to a single display resolves the issue.  I'm not running fedora, but I am running gnome 49 Wayland, and require it due to the mixed screen/refresh rates.  I like to reiterate that this only seems to be affecting mutter and not anything wlroots based, at least on my end.

**Comment by garrett** [comment]
For comparison: My 2 screens are the same resolution, refresh rate, and scale. (So just having more than 1 screen in Wayland is enough to trigger the instability.)

The version of GTK here is 3.24.51.

**Comment by antage** [comment]
I have 3 monitors with different resolution. I tried to disable 2 of 3 monitors in "Display settings" and I have the same results as @garrett. Darktable works fine with single monitor in wayland session.

All on Gnome 49, Archlinux.

**Comment by paperdigits** [comment]
@schwoens anyway you can test https://github.com/flathub/org.darktable.Darktable/pull/185 please?

**Comment by oleastre** [comment]
As it seems it only happens when running on Gnome 49, are there corresponding issue opened in Fedora or Gnome bug trackers ?

**Comment by garrett** [comment]
I asked on pixls.us about this issue, to try to figure out the scope a little better (as it requires running darktable on actual hardware, not just in a VM, due to multiple screen support). https://discuss.pixls.us/t/darktable-on-wayland-current-status-major-issues-and-workarounds/53430

Based on what everyone there said, and from my own testing, it does seem like a GNOME 49 regression on with some XWayland apps (including darktable) on Wayland (which is a bit of an issue, as there's no X session to fall back to).

Upstream bugs that look relevant:

- https://gitlab.gnome.org/GNOME/mutter/-/issues/4216 "Xwayland programs become unresponsive"
   - Mentions Thunderbird and RawTherapee. 
   - It doesn't mention multiple screens or single screen.
- https://gitlab.gnome.org/GNOME/mutter/-/issues/4397 "GNOME 49 XWayland Applications Become Non-Interactive When Moved to Secondary Monitor"
   - Doesn't say which app.
   - Does mention multiple screens.
   - Only sees the freeze after moving to the secondary screen.
- https://gitlab.gnome.org/GNOME/mutter/-/issues/4349 "xwayland overlay windows freeze with xwayland-native-scaling + scale-monitor-framebuffer"
   - This doesn't seem exactly like the issue we're seeing with darktable, but it _might_ still be related.
   - Mentions overlay apps like guake, tilda, ulauncher.
   - Doesn't mention multiple screens or not (but has multiple GPUs). 
   - Has scaling flags turned on. 

I also found a similar issue reported against GTK, which might actually be the same bug:

- https://gitlab.gnome.org/GNOME/gtk/-/issues/7809 "GTK application partially freeze but not crash"
   - This is reported against GTK for a GTK4 app, whereas darktable is still GTK3.
   - But it has the same symptoms, the same cause (upgrading to GNOME 49), and the author of the issue has 2 screens.

GNOME 49 has been released. I think it's already out in Arch Linux and openSUSE Tumbleweed. I know it's coming out soon in Fedora 43 and

**Comment by garrett** [comment]
I've opened up an issue for the submenu bug we've been seeing in native Wayland, where the whole menu disappears when trying to select a sub-menu: https://github.com/darktable-org/darktable/issues/19511

Right after filing the issue, I discovered this only happens when darktable is at the edge of the screen (as it usually is, when maximized), as the menu attempts to draw to the right (offscreen) instead of to the left (as it does in XWayland).

This is (from what I can see) the last blocker from darktable working in native Wayland vs. XWayland when running in Wayland. But I haven't done an exhaustive test. (Sadly, color management doesn't work in XWayland or native Wayland, at least on GNOME. That might be different on KDE however.)

The reason why I'm mentioning this is that it is still a little issue that would impact @paperdigits turning on Wayland native for the darktable flatpak, as well as for any of us who will be using GNOME 49 as-is (either an in already-released distro like Arch, openSUSE Tumbleweed, or Ubuntu 25.10... or in an upcoming one like Fedora 43).

**Comment by antage** [comment]
Gnome 49.1 still has the problem.

**Comment by solonovamax** [comment]
I'm able to reproduce this with KDE & KWin on Arch with Linux 6.17.4-arch2-1, so this doesn't seem like a gnome-only issue.

#19519 is probably related

The first time I encountered it, I had a full kernel cpu lockup. My suspicion is that this happened because I had previously upgraded my kernel, but not rebooted, so that had something to do with it. After a full reboot, if I open darktable, it still causes a graphics reset, however it does not cause a cpu lockup.

see: https://tech.lgbt/@solonovamax/115425165459544588

journal logs from cpu lockup: https://0x0.st/K2ZV.log

journal logs from graphics reset: https://0x0.st/K2Z3.log

if I run with `--disable-opencl`, then the issue does go away.

this no longer seems like a gnome issue to me, given that I'm encountering it on KDE

**Comment by garrett** [comment]
@solonovamax: I rebased to KDE and tried to trigger it quite a bit and didn't see the issue here on my computer with two screens. I also asked a lot of other folks to try it out with KDE and they also didn't see a freeze.

This bug happens in GNOME with or without openCL enabled.

I think you're likely seeing a different issue that's openCL related on your computer. (The bug you linked.)

**Comment by garrett** [comment]
I was able to reproduce this exact same issue with Inkscape too. It seems like it's a bug with some apps (so far, all GTK 3 apps... not sure if that's relevant) in XWayland on GNOME 49's Wayland session.

(With Inkscape, I saw the same things: XWayland would freeze exactly like how it happens in darktable. In native Wayland, it had problems with dropdowns, similar to the issue darktable has with submenus.)

As mentioned above, it's these two issues:
- https://gitlab.gnome.org/GNOME/mutter/-/issues/4216
- https://gitlab.gnome.org/GNOME/mutter/-/issues/4397

And, it seems like there's a merge request that reworks things a bit, and it _may_ fix the issue. It hasn't landed yet (as of the time of writing). Hopefully it fixes it, and hopefully it's merged and released soon:

- https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4731

**Comment by zzottel** [comment]
Should this be fixed in the nightly build? I'm still experiencing the issue with the Darktable 5.3.0+961~gf26491d2a9 AppImage (20251205) on Arch with Gnome 49.2.

**Comment by TurboGit** [comment]
Yes, should be fixed. I'm using Darktable on Wayland (GNOME 49.2) everyday without any issues. But I'm not using AppImage.

**Comment by zzottel** [comment]
Hm, the question is what's different here? I just tried setting GDK_BACKEND to wayland, but the issue stays the same. Only when I set my two screens to mirror mode, the problem vanishes.

The UI freezes randomly. Sometimes, it doesn't even draw the UI completely after start, sometimes it works for 10 minutes or so without problems.

I've never used an AppImage before. Could it be a problem that Darktable 5.2.1 is still installed normally in the system?

It issues a couple of warnings, not sure if they have anything to do with the problem:
```
/tmp/.mount_DarktakeJepa/usr/bin/../lib/libcrypto.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libssl.so.3)
Failed to load module: /tmp/.mount_DarktakeJepa/usr/lib/gio/modules/libgiolibproxy.so
Gtk-Message: 18:55:32.701: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:55:32.701: Failed to load module "canberra-gtk-module"
Fontconfig warning: using without calling FcInit()

** (darktable:203672): WARNING **: 18:55:33.514: [Lensfun] /home/zottel/.local/share/lensfun/slr-tamron.xml:3:1: Database version is 2, but supported is only 1!


** (darktable:203672): WARNING **: 18:55:57.775: atk-bridge: get_device_events_reply: unknown signature
```

If there's anything I can provide to help, please say so. Otherwise it's ok for me right now to just set my monitors to mirror mode while working with Darktable.

**Comment by TurboGit** [comment]
> GDK_BACKEND to wayland, but the issue stays the same

Sure as it is the default.

> I've never used an AppImage before. Could it be a problem that Darktable 5.2.1 is still installed normally in the system?

Don't know, but I suppose this is related to the AppImage which I don't use. And I have zero experience with AppImage.
