### ISSUE TITLE
Darktable doesn't start the first time

### ISSUE THREAD

**Issue by FinDale43** [darktable-org/darktable#19579]
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

When trying to start darktable for the first time (after PC has been hibernated) it doesn't open. Just get a white window - Darktable not responding. I close down darktable using task manager and then restart Darktable and all is good. 

### Steps to reproduce

1. Click Darktable icon
2. Cannot close window that appears in tip left hand corner so use taskmanager to end task.
3. Click Darktable icon - Darktable now starts up ok

### Expected behavior

Darktable should open properly the first time 

### Logfile | Screenshot | Screencast

<img width="1536" height="672" alt="Image" src="https://github.com/user-attachments/assets/71fcddc1-f9a9-4c3e-bb4c-a306466dc7bc" />

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

5.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Microsoft 11 Windows Pro

### Are you using OpenCL GPU in darktable?

No

**Comment by ralfbrown** [comment]
Does this also happen if you disable OpenCL in preferences or start darktable with `darktable --disable-opencl`?  ISTR a similar hang after suspend/resume due to the OpenCL drivers not correctly reinitializing on wake.

**Comment by FinDale43** [comment]
Hi there

The option to enable openCL is greyed out

<img width="952" height="931" alt="Image" src="https://github.com/user-attachments/assets/63f41b7e-9d98-49bc-b166-5a2e2b0665ea" />

**Comment by clemensgrimm** [comment]
still persisting in darktable-5.4.1-win64

**Comment by wpferguson** [comment]
It's fixed in master by #20424.  In the meantime, here is fixed file, 

[luarc.txt](https://github.com/user-attachments/files/25665024/luarc.txt)

Replace the `<darktable install directory>\share\darktable\luarc` file with the above on after removing the `.txt` extension

**Comment by wpferguson** [comment]
Fixed by #20424

**Comment by Bbawt** [comment]
I've been having the same issue of hanging on first startup on Win 11.  I tried the download of the luarc.txt file, removed the .txt and replaced the file under C:\Program Files\darktable\share\darktable but the issue persists.  Currently the only fix that works for me is running darktable.exe in Win8 compatibility mode.

**Comment by wpferguson** [comment]
@Bbawt  do you use the lua scripts?

**Comment by Bbawt** [comment]
@wpferguson actually no...newer laptop and I was using scripts on older computer.

**Comment by wpferguson** [comment]
@Bbawt when you start darktable are you going directly to darkroom or to lighttable or something else?

**Comment by Bbawt** [comment]
@wpferguson I'm just opening darktable via the shortcut the program provides after install so its trying to open to the lighttable.  First time use after booting up computer I get the hang and the partial white screen with "darktable not responding" in upper left corner. I then close the program and restart via the shortcut and it opens fine to the lighttable.  It will continue to open and close just fine until the computer reboots, then the first instance opening it hangs again.

I notice it does not hang if you change properties on darktable.exe under C:\Program Files\darktable\bin and apply "Run this program in compatibility mode for Windows 8" - but I recognize that's not the ideal fix.

**Comment by wpferguson** [comment]
I'm not sure why compatibility mode with Win 8 would fix it.  That kind of points to an OS issue.  However, the hang sounds very similar to the race condition we've seen and thought we had fixed.  So if it's the race condition then why would compatibility mode fix it?

I'm stumped at the moment.  I'll let my brain work on it and see if it figures anything out...

**Comment by Bbawt** [comment]
Someone suggested Win 8 compatibility on reddit: https://www.reddit.com/r/DarkTable/comments/1qr09ir/darktable_always_hangs_on_startup_then_works_fine/
So I tried it and it worked.  I wonder if compatibility mode somehow changes various loading times which doesn't result in the race condition?

**Comment by Bbawt** [comment]
I reverted darktable.exe back to normal mode (no compatibility mode).  I then deleted the luarc file.  Rebooted and darktable starts fine. I then downloaded your luarc.txt, deleted the .txt and put the file under \share\darktable\ and then rebooted.  Darktable then hangs again on first run.
