### ISSUE TITLE
Images upside down 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2310]
**Describe the bug**
on start of darktable all images in the current folder are flipped upside down.

**Platform (please complete the following information):**
 - OS: OSX
 - Version darktable 2.7.0+832~g853295f4e

**Comment by TurboGit** [comment]
Indeed :( Looks like this affect all currently imported images... This is because the previous orientation was broken. It is now fixed and tested against 8 images horizontal and vertical.

Let me think about the best way to fix current database!

**Comment by TurboGit** [comment]
A current solution is to remove the picture and reimport it.

Yet, we need something better.

**Comment by ptilopteri** [comment]
I do not see this with git829.9c9ed7e64-1090 on openSUSE Tumbleweed       
20190327
or I have failed to set the conditions which result in this.

**Comment by ptilopteri** [comment]
I do not see this upside down display on 2.7.0~git829.9c9ed7e64-1090.1 on openSUSE Tumbleweed 20190327, or I have failed to enable the conditions which display it.

**Comment by AxelG-DE** [comment]
I am on 2.7.0+833~g521127f62
re-imported my pictures of current selection and still have the flip upon opening darkroom

**Comment by TurboGit** [comment]
Should be fixed, I have found one pathological case in hundred of pictures.
