### ISSUE TITLE
Module on/off button do not react reliably

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5065]
**Describe the bug**

On/off button of module reacts unreliably. (easiest to see is tone equalizer)
I have to press the button sometimes twice or three times before module goes on or off.

**To Reproduce**

**Expected behavior**

on/off instantly

**Bisect gave me**

7600fb842fa792ad1719a1556374da2582990fec is the first bad commit
commit 7600fb842fa792ad1719a1556374da2582990fec
Author: Chris.Elston <chris.elston@blueyonder.co.uk>
Date:   Thu May 14 15:55:00 2020 +0100

    iop module gui focus shortcuts
    
    adds a new "focus module" shortcut to all iop modules to toggle gui
    focus and allows control-click on the module enable button to also
    toggle gui focus for the module (since this icon is now used to show
    focus- as well as enabled-state for modules)
    
    this is probably also a reasonable alternative solution for #4608 and
    gives the user the choice of showing crop & rotate gridlines (by
    assigning focus) or not prior to executing another module shortcut
    
    for crop & rotate the focus toggle also works as an alternative 'commit'
    button/shortcut

 src/develop/imageop.c | 30 +++++++++++++++++++++++++-----
 1 file changed, 25 insertions(+), 5 deletions(-)

**Platform (please complete the following information):**
 - Darktable Version: current master
 - OS:  Gentoo
 - OpenCL activated or no? --> Yes
 -  RTX 2070super with nvidia-drivers-440.82-r3

@elstoc as discussed today

**Additional context**

**Comment by elstoc** [comment]
As discussed I've been unable to reproduce this on the latest build (i.e. after #5050 was merged). As discussed in #5047 I've pushed a simplified version locally which might resolve it (https://github.com/elstoc/darktable/tree/ioptoggle2) but because I can't reproduce, I'm unable to confirm whether or not it has fixed the issue.

**Comment by AxelG-DE** [comment]
First of all, as I said in #5047 I am sorry for overlapping actions, I missed the notification.

But now, frankly speaking, this is beyond my abilities. When I click above link, I see that branch, but dunno what to do with that.

Also I need to admit, currently I run a -dirty code because of debugging what was behind this: https://github.com/darktable-org/darktable/issues/2724 yesterday night. 

But still; I could checkout prior 7600fb8 and do not have the issue, so there is a interaction...

So let me merge latest master first and I will try again

**Comment by elstoc** [comment]
#5050 (a7e64d9) was intended to fix the issue in 7600fb8 (and does fix it for me) so I'm surprised you still have the problem in current master. I'll await your retest

**Comment by AxelG-DE** [comment]
Just now tested latest master (no more dirty) problem3.1.0+1626~gbc5fbf8a6 and still have the problem :-/

**Comment by elstoc** [comment]
Ok I'm going to submit a PR for my alternate approach - it's much cleaner anyway and seems perhaps a little more responsive, so we'll see if it works.

**Comment by AxelG-DE** [comment]
sorry for being PITA, but I hope with testing, a no-dev can also do a bit to improve dt :)

**Comment by elstoc** [comment]
Not a PITA at all. There are many ways to contribute - I'm still new at gtk and event handling so it's entirely possible I've made some mistakes in my PR - it wouldn't be the first time. If you are able to test #5071 that would be very helpful.

**Comment by AxelG-DE** [comment]
I will test, however, might be not tonight. Stole already a lot of time from my lovely wife :)

**Comment by AxelG-DE** [comment]
Tested. 
Works like a charm!

**Comment by elstoc** [comment]
Knew we'd get there in the end. Thanks for your help @AxelG-DE

**Comment by AxelG-DE** [comment]
You are very welcom!
Is on me to say thank you. Taking someting serious, you cannot see, handle it, you cannot see, that is great. You devs making dt better and better, day by day. Thank you!
