### ISSUE TITLE
Crop and rotate doesn't retain the orientation settings when it differs from the image's orientation.

### ISSUE THREAD

**Issue by waxhead** [darktable-org/darktable#5326]
**Describe the bug**
The crop and rotate module doesn't appear to keep the settings from a crop where the orientation of the crop is different to the orientation of the image.

**To Reproduce**

On returning to the Crop and Rotate module the aspect ratio should be the same as applied before existing.

**Screenshots**

![cr-set](https://user-images.githubusercontent.com/8608051/83939702-5ebcb000-a822-11ea-85ff-506e3e3f9580.png)

![cr-return](https://user-images.githubusercontent.com/8608051/84144798-363fea80-aa9c-11ea-87fd-39c637564dcb.png)

**Platform (please complete the following information):**
 - Darktable Version: Lastest Git pull: 3.1.0+2016~g40a922d0e
Linux - Manjaro
 - OpenCL activated

**Additional context**

**Comment by elstoc** [comment]
I can't reproduce this on latest master on ArchLinux. BTW both the screenshots above are identical so don't show the issue. IIRC this was an issue on an earlier release but I thought it was fixed.

**Comment by GrahamByrnes** [comment]
> BTW both the screenshots above are identical

Oh good, I thought that was just me :-)

There are some weird things about the C&R UI, I'm not sure whether they are problems or "features"... it's very easy to allow a whole bunch of crops to pile up, without realising that you were cropping at each time.

I still have the just-slightly-off-centre image on my bugfix plate...

**Comment by waxhead** [comment]
You're right, they are both the same and that's my fault.  The two images I have show the differences.

I've done a quick screen cast and found something else, the crop is lost when the crop is in portrait orientation, you'll see this in the screen cast.


[Screencast from 07-06-20 08:45:27.zip](https://github.com/darktable-org/darktable/files/4741100/Screencast.from.07-06-20.08.45.27.zip)

**Comment by waxhead** [comment]
OK I have looked into this futher.

The issue with losing the settings of the crop is more related to when the orientation of the crop doesn't match the orientation of the image.

So a portrait image with a matching crop orientation will be fine.

Change the orientation of the crop to landscape and it loses the setting between closing and opening the module again.

This occurs the same when the image is in landscape and the orientation of the crop is in portrait.

Hope that's clearer.  I'll update the heading to make it clearer too.

**Comment by GrahamByrnes** [comment]
That makes sense: the aspect ratio is mostly stored as a ratio >=1, and then sometimes flipped for use.

I've been trying to get to the bottom of the logic of this (`iop/clipping.c L1355` & following) for other reasons for the last few days... and it might just be my head (yay covid :-( ) but it isn't obvious.
