### ISSUE TITLE
metadata and import tags not written on import with xmp files present

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6343]
openSUSE Tumbleweed 20200917
kernel-default 5.8.7
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0~git783.b2995917b
OpenCL loaded but not available
i7 12-core 36GB

darktable is executed with:  --library :memory:

when importing an image(s) with accompanying xmp file(s) the metadata
and tags designated in darktable are not written/updated in the imported 
xmp files.

**Comment by ptilopteri** [comment]
and darktable-3.3.0+792~g435335440
also fails to write tags and metadata to imports which already have xmp files.

**Comment by junkyardsparkle** [comment]
Isn't this the intended behavior when using `--library :memory:`? The man page states:

> You may also give ":memory:" as a library file in which case the database is kept in system memory - *all changes are discarded when darktable terminates*.

**Comment by ptilopteri** [comment]
I would not think so, writing the the xmp files is not writing to the library, which "--library :memory"  parameter deliberately disables.

Why would writing to the xmp files be disabled?  There is another config option to accomplish that.

**Comment by ptilopteri** [comment]
and fwiw, as I recall, it always did write to the xmp files as long as the configuration was chosen.

**Comment by junkyardsparkle** [comment]
I don't know, I've never used the option in conjunction with XMP sidecars before, and never really thought about it. I guess it depends on whether the option is intended to imply "no persistent side effects" or only "no library.db file". The "all changes are discarded" language suggests the former to me, but I don't really have an opinion either way. In any case, it should probably be made clear in the docs, I guess.

**Comment by ptilopteri** [comment]
previous behaviour was to write to xmp files unless configured not to.  I was not implied.
tks

**Comment by parafin** [comment]
`--library :memory:` intention is to be used with "write sidecars" option enabled. Not saving changes anywhere doesn't sound useful at all to me.

**Comment by TurboGit** [comment]
I think this has been fixed in f20f484f1c. Tested with current master this works for me.

**Comment by ptilopteri** [comment]
issue is still present in d7d10f14c

**Comment by ptilopteri** [comment]
is not working in current master, 96de08c0d

**Comment by ptilopteri** [comment]
still does not apply xmp information to existing files when imported
  darktable --library :memory /path/file/

**Comment by ptilopteri** [comment]
still a problem

**Comment by ptilopteri** [comment]
bing

**Comment by Nilvus** [comment]
@ptilopteri: is this still an issue in actual master?

**Comment by ptilopteri** [comment]
yes, still fails on 3.5.0+2589~g4b2a53d58

**Comment by johnny-bit** [comment]
Just so i can understan how to test it - what should be in xmp files before importing to darktable, what metadata and where to write and what xmp content do we expect to get?

**Comment by ptilopteri** [comment]
sorry, when testing today with 3.5.0-2590-ga7ab4c194, tags are written
as expected.  I do not know what has changed except a newer issue of dt.
My system has not been updated since the failing test of 3.5.0+2589~g4b2a53d58

you can close or I will.  If I notice again, I will re-open.  tks

**Comment by johnny-bit** [comment]
Please close yourself - that way you'll be in controll of opening/closing.

as for checking - please write instruction on how one can reproduce the problem step-by-step if you manage to reproduce yourself.

**Comment by ptilopteri** [comment]
previous conditions to reproduce:
  open dt as:  darktable --library :memory:
  import image with "apply metadata" selected and a "new tag"
  result does not have "new tag" 

closing as currently not reproducable.

tks
