### ISSUE TITLE
META ISSUE : pipeline reordering for 3.6

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#8634]
Please list, gather and synthesize current issues with current default pipeline order (3.0).

So far, we have : 

- [ ] Vignetting should be in scene-referred pipeline
- [x] ~~Retouch & Spot removal may be better before crop/rotate ?~~ Bad idea, see  #8675.
- [ ] Framing needs to be movable in the pipe
- [ ] Local contrast may be better before filmic / base curve ?
- [ ] Crop & frame may be on the same side of rotation as perspective correction ?
- [ ] Remove the IOP fence on borders

**Comment by elstoc** [comment]
Unless we plan to deprecate spot removal this should also be moved before crop/rotate. Not sure I can comment on local contrast/vignetting but I don't have an issue with moving them if we think it will be an improvement.

**Comment by Nilvus** [comment]
>     * [ ]  Retouch & Spot removal may be better before crop/rotate ?

As @elstoc suggest, I think spot removal could (and should) be deprecated. But they seems good for me after crop/rotate. I prefer crop/rotate before retouch (something on border images could disappear if rotate/crop. So no need to retouch those parts for example. But before could be ok too.
 
>     * [ ]  Local contrast may be better before filmic / base curve ?

I have tested both and find for my needs that it's better most of the time after filmic (I don't use base curve) and only sometimes before. So I'm more after.

Nothing to add for other points.

**Comment by elstoc** [comment]
> They seems good for me after crop/rotate. I prefer crop/rotate before retouch (something on border images could disappear if rotate/crop. So no need to retouch those parts for example. But before could be ok too.

If you want to take the source for retouch/spots from outside of the cropped area, then crop/rotate must come _after_ those modules. This is a very common use case for me and I find myself reordering these modules often. The current order means that both source and target shapes must be placed inside the cropped area.

**Comment by AlicVB** [comment]
agree with @Nilvus : spot can be deprecated.
For retouch position, I think it's better before crop&rotate. One usecase : 
- you make some correction and then you crop your image for creative reasons (I often have multiple version of the same image with different crop). If you have some retouch with the source outside the visible area (but on the "base" image) you have a problem

**Comment by jenshannoschwalm** [comment]
I am not sure we can just move the crop&rotate to another position in the pipeline with respect to keeping developed images as they are.
1. any distorting module (liquify, retouch ..) could refer to areas currently outside the crop and suddenly it's inside. Are we sure this is always corrected precisely?
2. modules might calculate data from available input as sort of reference (defringe?) could it be that those parameters change without notice?

wouldn't this mean to introduce a new module order or at least reposition crop&rotate only for new edits?

**Comment by elstoc** [comment]
> wouldn't this mean to introduce a new module order or at least reposition crop&rotate only for new edits?

That's what I assumed we were discussing, yes. Definitely wouldn't want to reorder the modules for existing edits.

**Comment by aurelienpierre** [comment]
I have mixed feelings about deprecating spots. The retouch module is far from perfect in terms of results and a lot slower. 

> I am not sure we can just move the crop&rotate to another position in the pipeline with respect to keeping developed images as they are.

We are discussing here a new default, which will not affect older edits since the pipeline order is written in DB along with editing history.

**Comment by ralfbrown** [comment]
The cloning tool in the retouch module is functionally equivalent to the spot removal module, and in fact started out as a copy of same (obvious from the code and comments).  It should also be essentially the same speed -- it's the heal tool that is slower due to the extra  computation in trying to adapt the source region to the destination.  IME, "heal" nearly always gives superior results compared to "clone"; the exception is patching large mostly-uniform areas with a dramatically different color at one edge of the destination region than the other (e.g. filling in missing sky on a handheld stitched panorama).

Regarding pipe order, spots/retouch should definitely come before the modules which can crop the image (perspective correction as well as c&r).  I would also argue that liquify is better placed after spots/retouch (but still before c&r/perspective).  In the current ordering, placing a shape over top of a warp from liquify can lead to odd-appearing shapes, including decidedly non-smooth outlines, and unexpected results for clone/heal.

**Comment by Nilvus** [comment]
And related to #7473

**Comment by GustavHaapalahti** [comment]
I have noticed that defringe does not work very well with the 3.0 order when using it on astro photos. The stars that have fringing are blacked out. If I move defringe before input color profile, it works well.

**Comment by rawfiner** [comment]
I agree with @GustavHaapalahti , defringe is better before input color profile. In case of strong chromatic aberration, luminance can become very dark due to some chromatic aberration: correcting them before input color profile avoids this issue.

**Comment by aurelienpierre** [comment]
Defringe is an Lab module that de-chroma edges in Lab. There is no Lab space before input color profile (aka matching sensor RGB to XYZ), hence no chroma, so that's all bogus. I'm not sure why it behaves better, before, but it surely doesn't do what's advertised.

> IME, "heal" nearly always gives superior results compared to "clone"; the exception is patching large mostly-uniform areas with a dramatically different color at one edge of the destination region than the other (e.g. filling in missing sky on a handheld stitched panorama).

Healing gives correct results if you correct destination patches far from edges with source patches far from edges. Any edge nearby the source or the destination messes up the output, especially since it is not possible to rotate the patches to match the edge direction source vs. destination. Also, a quick look at the code shows that it uses an algo tuned for 8 bit uint, which is not what we do here. Anyway, point being : I don't trust that module too much.

> Regarding pipe order, spots/retouch should definitely come before the modules which can crop the image (perspective correction as well as c&r).

I'm not so sure. Because of the utter sensitivity to edges of the retouch/spot stamps, if the image is not yet perspective-corrected before going to retouching, that reduces a lot the number of candidate patches to sample.

> I would also argue that liquify is better placed after spots/retouch (but still before c&r/perspective). In the current ordering, placing a shape over top of a warp from liquify can lead to odd-appearing shapes, including decidedly non-smooth outlines, and unexpected results for clone/heal.

The problem then is that the liquify control doesn't happen in viewport space, which makes coordinates mapping odd in GUI. Also, it does make more sense to resculpt the shapes after the uniform geometric distortions (always edit general -> peculiar, uniform -> local). The true problem here seems to be that masks higher in the stack follow the liquify distortions, and I don't see why. The output of liquify should be treated as a new image, and I see no point in tracking its distortions.

**Comment by ralfbrown** [comment]
> > Regarding pipe order, spots/retouch should definitely come before the modules which can crop the image (perspective correction as well as c&r).
> 
> I'm not so sure. Because of the utter sensitivity to edges of the retouch/spot stamps, if the image is not yet perspective-corrected before going to retouching, that reduces a lot the number of candidate patches to sample.

The stamps pass through the distort functions of the preceding modules, so you get the same candidates either way.

**Comment by aurelienpierre** [comment]
Ok so that explains a lot of weird behaviours I have seen. Is there even a use case for carrying-on distortions along the pipe like that ? From where I sit, it only creates problems and odd misbehaviours.

**Comment by elstoc** [comment]
There's some discussion of these sorts of things in #3904 if it helps

**Comment by jenshannoschwalm** [comment]
> s there even a use case for carrying-on distortions along the pipe like that ?

Masks?

**Comment by rawfiner** [comment]
> Defringe is an Lab module that de-chroma edges in Lab. There is no Lab space before input color profile (aka matching sensor RGB to XYZ), hence no chroma, so that's all bogus. I'm not sure why it behaves better, before, but it surely doesn't do what's advertised.

I understand. Defringe itself may indeed behave worse before input color profile than after. Having it before input color profile helps because it improves behavior of input color profile, which behaves badly in presence of chromatic aberration. (in other words: [bad defringe behavior + good input color profile behavior] is visually better than [bad input color profile behavior + good defringe behavior]).

**Comment by aurelienpierre** [comment]
For masks, you only need to map the coordinates of the mask center through distortions (like an anchor, you record the pixel to which it should be attached), but not the whole mask shape. Since the mask shape is drawn in viewport reference, it should respect the viewport shape.

**Comment by aurelienpierre** [comment]
>Having it before input color profile helps because it improves behavior of input color profile, which behaves badly in presence of chromatic aberration.

Input color profile is a linear map, how could it be subjected to frequential artifacts ?

**Comment by jenshannoschwalm** [comment]
Remember raster masks. The get transformed pixel-wise.

**Comment by aurelienpierre** [comment]
> Remember raster masks. The get transformed pixel-wise.

Again, for what purpose ?

Distortions happen early in the pipeline. I think, after the last distorting module, we can just set the image geometry in stone and assume the pixel matte is static for the rest of the operations to come. Carrying geometric distortions is only going to create inconsistencies between viewport (GUI) and image pixels (pipeline).

**Comment by jenshannoschwalm** [comment]
> Again, for what purpose ?
A mask used as a raster source can be from any module, whereever it sits in the pipeline.

**Comment by aurelienpierre** [comment]
But the modules supporting masks all come after the distortion modules.

**Comment by AlicVB** [comment]
@aurelienpierre : not sure we speak of the same thing, but masks points, etc... are always defined in the initial image space. So we need to be able to transform (and backtransform) coordinates from any point of the pipe to the initial image space. This is needed so we don't enforce the user to edit the image in a defined order. Take this simple example : 
- you define a path mask to select an object in the image and apply whatever effect you want on it
- then you find that you want to change the rotation value (whatever the reason, creative or corrective)

=> you want your carefully defined mask to still follow your object !

Same also apply for "on-canvas" drawings...

...again, maybe I've not understood what you was saying;)

**Comment by aurelienpierre** [comment]
@AlicVB that goal is simply unsustainable with the local distortions we have now. I get it for uniform distortions, like perspective and rotation, but #3904 clearly shows the limits of this design. 

I'm going to say that if the user has to change the orientation of the pic long after he started drawing shapes, he needs to seriously rethink his editing method.

**Comment by rawfiner** [comment]
> Input color profile is a linear map, how could it be subjected to frequential artifacts ?

Actually, the problem is defringe suppose luminance is not erroneous, which is not right in case of chromatic aberrations. But the discontinuity in luminance due to a chromatic aberration can be much higher after input color profile than before.

For example, with a chromatic aberration between a dark tree and the sky, which gives a blue fringe:
G: `——_____`
B: `————___`
(sky on the left, tree on the right, chromatic aberration is visible where blue is erroneously high while green is already low)

After input color profile, green value can become negative if there is a negative coefficient for blue in the input color matrix, even if that coefficient is very small, because in our example blue is very high compared to green.
Also, if we consider that luminance is mostly green, before input color profile our green channel is error free (we can assume that one of the 3 channels is a reference and the other 2 are erroneous), while after input color profile the error has spread over all channels.
So after input color profile we get in such a case a much stronger error on luminance.

In our example, if we look at luminance before (BL) and after (AL) input color profile we get (I'll use numbers for BL and AL, I don't manage to do it with ASCII art):
_G: `——_____`
_B: `————___`
BL: `3322111`
AL: `3300111`

**Comment by TurboGit** [comment]
> I'm going to say that if the user has to change the orientation of the pic long after he started drawing shapes, he needs to seriously rethink his editing method.

Well sometime (and I did that many times) you edit a picture and at the end you find that it is better with some other orientation. This may be true for standard landscape or portrait to flip horizontally to change the reading, but also true for architecture details mostly graphic things that you can have in different orientation.

So I agree with @AlicVB , the fundamental design of masking in the original space must be kept.

**Comment by AlicVB** [comment]
> he needs to seriously rethink his editing method.

not really if you speak about "creative" distortions...

and anyway, going back to a static order in term of user interaction is not really an option imo, even if it's great on the paper, I guess that I'm not the only one who need to reajust few things sometimes (either forgotten stuff, or wrongly set, or not enough precise)

**Comment by aurelienpierre** [comment]
> So I agree with @AlicVB , the fundamental design of masking in the original space must be kept.

The original design assumed only non-destructive modules. Retouch and liquify modules are clearly raster modules. In fact, dt is probably the only non-destructive editor to have them. That's bending its purpose a lot. In any raster editor, when you change low layers, you void the higher layers, that's how it is. So there are decisions that need to be dealt with early. 

Right now, I don't care what should/should not be kept. We have several problems of shifting between GUI drawn masks and actual pixel masks, the most severe of them happening with lens correction (which has been there forever and is reasonably simple because it's uniform, so it doesn't even have the excuses liquify has). Less sever issues is the retouch clone/heal sampling, because when you sample areas that look alike in viewport, in the pixel pipe they might actually be distorted and different, so there is no way to know what you actually sample.

In both instances, the GUI feedback is completely misleading and there is no way to guess what's really going on in the pipeline.

Thus, right now, for the sake of allowing hypothetic second thoughts on the first stages of the pipeline, we are degrading core features in ways that cannot be fixed. Consistency between what is drawn and what appears on screen is not optional here. **Interactions happen in viewport space**, GUI feedback needs to honor that.

**Comment by elstoc** [comment]
If we're talking about continuing to draw the _points_ of the mask (the nodes of a curve, the centre of a circle etc.) in the co-ordinates of the original image, but drawing the _actual shape_ onto the distorted image (the viewport) that seems fine to me, since the points will still be placed on the same image features if you change the distortion subsequently, but the interpretation of the shape between those points will be much more predictable and will match what it looked like when the user originally _placed_ the shape.

**Comment by aurelienpierre** [comment]
![image](https://user-images.githubusercontent.com/2779157/114314231-2947b980-9afa-11eb-8b2e-8d99691a8de4.png)

Like that ? Isn't it already what's supposed to happen ?

**Comment by parafin** [comment]
You can't save mask in coordinates other than original picture, because basically any module (certainly liquify) can be disabled (e.g. temporary). Having masks bound to output of some module is simply impossible (well, will lead to very strange results which will make this feature unusable).

**Comment by aurelienpierre** [comment]
> Having masks bound to output of some module is simply impossible (well, will lead to very strange results which will make this feature unusable).

You can bound masks to pixel matte coordinates ± zoom and translation, then let the distorting modules populate the matte as they see fit. That defines a fence between the distorting modules and the masking modules, which isolates them entirely and allow to always assume matte reference == viewport reference. Since mask feathering is available, drawn mask can follow objects in a sloppy way without consequences, so micro-distortions of liquify should not be a problem.

**Comment by elstoc** [comment]
> Isn't it already what's supposed to happen?

I dunno but it's not what _actually_ happens (again see #3904)

**Comment by aurelienpierre** [comment]
So it's even worse than what I thought. Does anybody know what **actually** happens in there and if the issue is not merely some maths mistake in the transforms ?

**Comment by parafin** [comment]
> > Having masks bound to output of some module is simply impossible (well, will lead to very strange results which will make this feature unusable).
> 
> You can bound masks to pixel matte coordinates ± zoom and translation, then let the distorting modules populate the matte as they see fit. That defines a fence between the distorting modules and the masking modules, which isolates them entirely and allow to always assume matte reference == viewport reference. Since mask feathering is available, drawn mask can follow objects in a sloppy way without consequences, so micro-distortions of liquify should not be a problem.

What exactly will this solve? Being able to draw straight lines after some tricky distortion module? If it's just a UI problem, then there's probably no need for backend changes.

**Comment by aurelienpierre** [comment]
> What exactly will this solve? Being able to draw straight lines after some tricky distortion module? If it's just a UI problem, then there's probably no need for backend changes.

Being able to draw exactly on one pixel from the GUI on the pipeline, without having to guess pixel shift between both references.

**Comment by elstoc** [comment]
As an example, you apply lens correction, which fixes a curved horizon, but you want to then apply a straight gradient mask to that horizon. Perversely, though you've fixed the horizon, now it's the mask that's curved, because the mask started off straight (w.r.t. the original image) and has been made curved by the lens correction. This was the primary use case for being able to curve the gradient mask iirc.

**Comment by aurelienpierre** [comment]
> As an example, you apply lens correction, which fixes a curved horizon, but you want to then apply a straight gradient mask to that horizon. Perversely, though you've fixed the horizon, now it's the mask that's curved, because the mask started off straight (w.r.t. the original image) and has been made curved by the lens correction. This was the primary use case for being able to curve the gradient mask iirc.

So that means there is no backtransform implemented between drawing and saving mask nodes. Drawing happens on the RAW image that is not visible in viewport. But I guess that backtransform would require the mask to be rasterized in viewport space before running, which makes it hardly suited to save vector nodes in RAW space.

Aka ditch RAW coordinates.

**Comment by elstoc** [comment]
> Aka ditch RAW coordinates

And we're back into enforcing workflow and rework when you change your mind, which I think was how it used to be. Personally I'd rather live with the current limitations than that because I do a lot of changing my mind about distortions later in my workflow.

Again, though, it's not the _nodes_ that are the problem but that the rest of the shape is drawn on the raw. Is there not a way that we could store co-ordinates and calculate shapes at different points in the pipe?

**Comment by ralfbrown** [comment]
Shapes are drawn by plotting their control nodes and a moderately large number (up to several hundred for circle/ellipse, up to 100 or so per control node for path and brush) of border positions for both the shape proper and the outer edge of the falloff region in RAW space and transforming them through the currently-applied module distortions.  The resulting border points are then connected to draw the shape in the GUI, and the shape is filled in between the transformed points to form the stamp that is used to actually apply the shape.

**Comment by AlicVB** [comment]
there IS backtransform (and transform) implemented for each "distort" iop (maybe some are wrong or accurate enough, but that's another story)
The problem about gradient line and so on is different : it's due to gradient saved as a "line" == 2 points at images extremities (or one point and an angle, don't remember) on the initial image reference. So you have a curved line on screen...

Now we can change that (iirc, there's something like that for graduated density) : it's just a matter of saving the right list of points in order to be sure to have a right line on screen : 
- you transform the line in a series a point.
- you transform them in the initial image reference
- you save the result (which will NOT be a straight line in the initial image ref, but straight where you want)

But the limitation is that any change in a distort module after that may provoke unexpected results (simple example : you disable lens correction)

**Comment by TurboGit** [comment]
And don't forget that a mask can be reused in any module at any level in the pipe. Changing the current way of working is just asking for trouble and will probably leads to more issues that there is at the moment.

And yes I suppose the current issues are math errors or rounding issues. We had some that were fixed and today we have something quite good.

**Comment by AlicVB** [comment]
In fact, I think that I don't really face this problems because I mainly use paths masks with a lot points, so the result is exactly what I want on screen, whatever the distortion in the image pipe.
So for paths (with lot of points) or drawn masks, I guess the problem is not really here.

So the problem remains "only" for "predefined" shapes (circles, ellipses and gradient) gradient is really a problem, but for the other... maybe we should just say somewhere that "sometimes circles can appear distorted. If you need very accurate results, better use paths to be more precise"

**Comment by aurelienpierre** [comment]
> And we're back into enforcing workflow and rework when you change your mind, which I think was how it used to be. Personally I'd rather live with the current limitations than that because I do a lot of changing my mind about distortions later in my workflow.

Just because modules can be reordered now still doesn't mean that the pipeline can and should be an oktoberfest. Operations still have a legitimate order dictated by technics, and a lot of silly abuses dictated by a false feeling of freedom. People have learned, in Gimp or Photoshop, that they are not allowed to change their mind about early layers, they know how to work with this limitation.

I'm against keeping up with rigid limitations if it goes in the way of proper behaviour. Something has to give. There is no point in drawing if you can't reach the pixel you aimed at. By the way, how often do you use distortion AND drawn masks at the same time ? 

Personally, I use lens correction 100% of times, drawn masks between 30 to 50%, but rarely more than 3-4 shapes and I draw them loosely since mask feathering deals with edges for me. Fixing perspective and orientation is the first thing I do after filmic and exposure (used without no masking), I crop/reframe less than 2% of times. I use liquify occasionally to fix the shape of squeezed body fat, but honestly the magnitude of the changes is usually too small for a feathered mask to notice.

> Again, though, it's not the nodes that are the problem but that the rest of the shape is drawn on the raw. Is there not a way that we could store co-ordinates and calculate shapes at different points in the pipe?

> But I guess that backtransform would require the mask to be rasterized in viewport space before running, which makes it hardly suited to save vector nodes in RAW space.

**Comment by aurelienpierre** [comment]
> And don't forget that a mask can be reused in any module at any level in the pipe. Changing the current way of working is just asking for trouble and will probably leads to more issues that there is at the moment.

We don't care. The last module doing distortion is retouch, the first module doing masking is exposure, that comes right after. Masking modules all see the same geometry.

**Comment by elstoc** [comment]
> By the way, how often do you use distortion AND drawn masks at the same time ?

I always use lens correction so every time I use drawn masks I also use distortion, and I use masks quite a lot. My "travel camera" has some quite big lens distortion too. I also do a lot of crop/reframing because I'm a rubbish photographer. I use keystone more and more recently, since I'm photographing more buildings than I used to and tilt/shift lenses are way out of my price range.

Again though, I'm not talking about changing module order I'm talking about adjusting rotation, orientation, keystone etc. after I've done retouch and tone correction, for which I often still use drawn masks. If you're saying that a slight change to rotation or keystone adjustment will require me to redo my masks, I'm not really ok with that. If not, then I've misunderstood somewhere.

**Comment by aurelienpierre** [comment]
Quick test just now : trying to clone a dandelion on the grass with a fine brush.

With lens correction on : the GUI shapes are at the right place, but I duplicate grass instead.
![Screenshot_20210411_203015](https://user-images.githubusercontent.com/2779157/114316674-cf002600-9b04-11eb-92db-556fdf85ad97.png)

With lens correction disabled : the GUI shapes are misplaced, but I get the dandelion.
![Screenshot_20210411_203034](https://user-images.githubusercontent.com/2779157/114316672-cdcef900-9b04-11eb-8c9d-e5e6a11a10a6.png)

This is not more acceptable to me than having to move some masks if after having some cropping second thoughts. I mean, how am I supposed to spot the dandelion ?

**Comment by aurelienpierre** [comment]
> there IS backtransform (and transform) implemented for each "distort" iop (maybe some are wrong or accurate enough, but that's another story)

I know there is, my point is it doesn't run at drawing time to convert viewport coordinates to RAW coordinates. Otherwise, the straight gradient would be saved as a bended one, and would be rendered both in viewport and in pipeline, as a straight line.

**Comment by parafin** [comment]
There is a bug apparently, doesn't mean original concept is flawed.

**Comment by aurelienpierre** [comment]
> There is a bug apparently, doesn't mean original concept is flawed.

The original concept is flawed if it doesn't allow a bugfix.

**Comment by AlicVB** [comment]
@aurelienpierre : for me, the example you give with retouch clearly indicate that there's a bug in retouch iop.

**Comment by jenshannoschwalm** [comment]
At least for lens module there is no exact backtransform. @TurboGit did a nearing solution in

`commit 18c195235a152bc98ef4176851fbf30ad8840111`

**Comment by TurboGit** [comment]
> I mean, how am I supposed to spot the dandelion ?

By fixing the bug in dt. Please open an issue with precise description of the issue. With the current design everything should work (I don't see why it could not), maybe not 100% accurate but very close and so acceptable.

**Comment by TurboGit** [comment]
> By the way, how often do you use distortion AND drawn masks at the same time ?

All the time.

**Comment by aurelienpierre** [comment]
> By fixing the bug in dt. 

![Screenshot_20210412_041733](https://user-images.githubusercontent.com/2779157/114332205-09d67e00-9b46-11eb-9a4e-8daf9307ec68.png)

Nevertheless, all these strokes have been drawn with the same brush size and shape… yet none of them has a shape consistent with the original brush, nor with the other strokes. 

The bug is the design.

**Comment by parafin** [comment]
You do understand that it's a different issue than the previous one you posted? The latest one is indeed design limitation, not a major one IMHO, but a way to alleviate it was already mentioned - instead of using shapes like circles and lines, curves/paths can be used with enough control points. The problem with that approach is that it won't be possible to edit shapes like shapes later on.
Using raster masks isn't viable option due to its size, and I don't see how vector masks in viewport space can work if we allow changing settings of distortion modules after mask was created (and we do and don't want to remove this possibility).
So I would suggest to look into mentioned direction - converting shapes into curves/paths.

**Comment by aurelienpierre** [comment]
> Using raster masks isn't viable option due to their size, and I don't see how vector masks in viewport space can work if we allow changing settings of distortion modules after mask was created (and we do and don't want to remove this possibility).

Jeez, now I wonder how Photoshop, Gimp, Krita and the likes survive with a 100% raster layers architecture…

I have been doing tests, and bypassing `module->distort_transform(module, piece, points, points_count);` and `module->distort_backtransform(module, piece, points, points_count);` in `/dev/develop.c`, and it makes mask work properly from a GUI standpoint. I believe it is possible to simple translate the mask nodes when the image geometry is changed and then keep shapes and nodes in viewport space. That could be an option in the mask manager (switching between viewport reference or raw reference), with an "update" button that performs the coordinates changes upon request.

**Comment by parafin** [comment]
> > Using raster masks isn't viable option due to their size, and I don't see how vector masks in viewport space can work if we allow changing settings of distortion modules after mask was created (and we do and don't want to remove this possibility).
> 
> Jeez, now I wonder how Photoshop, Gimp, Krita and the likes survive with a 100% raster layers architecture…

I suspect by having big save files. I'm not sure it can work in case of darktable. E.g. if you have a couple of iops with masks, their size will be bigger than original RAW. Granted, masks usually can be compressed much better, but still it's a lot of overhead per each image.

> I have been doing tests, and bypassing `module->distort_transform(module, piece, points, points_count);` and `module->distort_backtransform(module, piece, points, points_count);` in `/dev/develop.c`, and it makes mask work properly from a GUI standpoint. I believe it is possible to simple translate the mask nodes when the image geometry is changed and then keep shapes and nodes in viewport space. That could be an option in the mask manager (switching between viewport reference or raw reference), with an "update" button that performs the coordinates changes upon request.

You end up with the same exact problem - you can't just "translate" circle after generic geometry change to still be mapped to the same pixels, because distortion can change the shape of circle. If you know how to solve this, then you might as well fix the issue for the current design. If you mean something different or you assume that some compromise is acceptable, please be more explicit and specific about what you suggest exactly. I don't see any silver bullet solution as of yet.

**Comment by TurboGit** [comment]
I agree with parafin, I don't really understand. You want a circle on the view port after perspective correction. Why no. But if you remove the perspective correction the circle can't be anymore a circle anyway if you want it to map to the same pixels. So you need to distort it. The goal in dt is when you place a shape on the picture you end up enclosing the same pixels set at any place in the pipe and after or before whatever pixel distortion applied or removed. That's why a shape is mapped to the original picture as it is a safe and stable space coordinate.

Not an easy goal, but quite well handled today. And again if there is bugs we need to fix them.

**Comment by aurelienpierre** [comment]
> You end up with the same exact problem - you can't just "translate" circle after generic geometry change to still be mapped to the same pixels, because distortion can change the shape of circle. If you know how to solve this, then you might as well fix the issue for the current design. If you mean something different or you assume that some compromise is acceptable, please be more explicit and specific about what you suggest exactly. I don't see any silver bullet solution as of yet.

A circle is defined by its center and radius. Right now, when you draw a circle in viewport, actually you draw a circle in the RAW image grid. The resulting mask in viewport is an ellipse, properly positioned, but ill-shaped. That's unacceptable, again because what is drawn is what should be rendered. When I mean do draw a circle, I expect it to be a circle in the final image, no matter what happens in the pipeline.

To ensure shapes are respected, what is needed is only a coordinates transform of the shape centers, not over the full shape. That way, the drawn geometry moves with its pixel anchor, but preserves its shape.

>  The goal in dt is when you place a shape on the picture you end up enclosing the same pixels set at any place in the pipe and after or before whatever pixel distortion applied or removed. That's why a shape is mapped to the original picture as it is a safe and stable space coordinate.

Having the same pixels wrongly enclosed by a wrong shape is a poor consolation for **circle** drawn masks becoming **ellipses** or **linear** gradients becoming **bended** in the actual rendering. I don't care for consistency in wrong behaviour. I'm asking for a circle, I want my circle. Excuses will not make an ellipse a circle. Especially since circles are to be found in images only **after** perspective correction, so there is no point in using geometric regular shapes on non-corrected RAW images (with barrel and perspective distortions) : there aren't any.

**Comment by elstoc** [comment]
> To ensure shapes are respected, what is needed is only a coordinates transform of the shape centers, not over the full shape

This was basically what I was saying. The _points_ need to be consistent (the centre of a circle, the nodes of a path, the centre point of a gradient) and to do that you can define them in raw space. Then you transform those points to the viewport (the end of the distorting modules) and draw the shapes respecting those points. If it can be made to work I'm all for it, though possibly things like rotation/orientation/feather size might be harder.

**Comment by parafin** [comment]
So the compromise you're fine with is that changing distortions can result in different pixels becoming part of the mask. You just want your circles staying round. That's may be a reasonable choice for practical reasons. It's just not the only choice, and some people will disagree with it.

**Comment by aurelienpierre** [comment]
The GUI button label says "draw a circle". The GUI button icon shows a circle. The GUI cursor for the brush shows a circle. The GUI feedback for the drawn shape shows a circle.

But the GUI mask renders as an ellipse. 

Sorry but I fail to see how it's just "some choice". Whatever brush you hold (even in real life), you expect it to deliver a stroke of the same shape, which is why you chose it in the first place. Not some surprise shape projected onto a virtual reality you have no way to guess nor see.

If you just need to mask pixels, you use a parametric mask. But drawing is pretty straightforward… Ask a kid if an ellipse is a circle, you will see.

The other choice would be to display the RAW image without any geometric correction when drawing masks, because that's what you actually draw on. But even that is not consistent.

**Comment by elstoc** [comment]
In the end it's all just a choice of workflow, and a choice of restrictions. 

@aurelienpierre says do all your distortion first and then have masks that conform to the shape that's shown on screen. Presumably, though, an alternative workflow (in the current version of darktable, and without any changes) would be to do your distortions _last_, after you've finished doing work that requires masks/shapes. When you draw the shapes they will conform to exactly what's shown on screen. Only when you're finished do you implement your distortions, but by then you're already working on a fully-edited image. If you want to go back and alter your shapes later, switch off the distorting modules, fix your issues, then switch them back on.

I'm aware I've made arguments both ways in this thread, but that's because I don't think there's necessarily an easy choice here. But you _can_ define a workflow that works with the way darktable is built now.

**Comment by parafin** [comment]
The choice is how distortion should apply to a drawn mask. One may expect that if you draw a circle and then distort the image, then the circle will get distorted too (e.g. become an ellipse). That is quite reasonable expectation too, which will get broken by your approach and should work with current. Your choice is to ignore that problem, even if you don’t acknowledge it as a choice. The fact that current implementation is buggy is quite irrelevant to the conceptual design of the masks feature. But it may indeed affect the choice of design if it’s not easily fixable.

**Comment by aurelienpierre** [comment]
> One may expect that if you draw a circle and then distort the image, then the circle will get distorted too (e.g. become an ellipse). That is quite reasonable expectation too, which will get broken by your approach and should work with current. 

To achieve this goal, then you move the distortion modules up the pipe, after your masks. That's how it is in any raster image processing software. darktable abides by the same layering logic : modules = operations = layers, and order of operations in the pipe dictates the order of settings. Its surprising that we are still getting dead-set on a non-destructive mindset when the features we are discussing here are clearly raster-based internally and call for the same logic as Gimp or Photoshop.

I mean, nobody objects here that changing exposure early in the pipe might void your parametric luma masking later in the pipe. You are all very comfortable with that. Why is it that drawn masks should abide by another logic, to tolerate second thoughts and clumsy workflows at the expense of accuracy and proper behaviour ? Painting should be a flawless and organic experience.

You can try all you want to stick masks to RAW coordinates : it's doomed to fail. The lens distortions in Lensfun lib are 5th or 7th order polynomials in 2D, they are not invertible in general. So that goal will always meet a dead-end, it will be at best inaccurate, with inaccuracy getting worse as screen resolutions increase. Therefore that constraint should be lifted. There is only madness in trying to cope with impossible constraints.

**Comment by TurboGit** [comment]
> But the GUI mask renders as an ellipse.

Because there is distortion. Everybody can understand that. I had never had question about that during my course on dt at my photo club.

**Comment by TurboGit** [comment]
> @aurelienpierre says do all your distortion first and then have masks that conform to the shape that's shown on screen. Presumably, though, an alternative workflow (in the current version of darktable, and without any changes) would be to do your distortions _last_, after you've finished doing work that requires masks/shapes. When you draw the shapes they will conform to exactly what's shown on screen. Only when you're finished do you implement your distortions, but by then you're already working on a fully-edited image. If you want to go back and alter your shapes later, switch off the distorting modules, fix your issues, then switch them back on.

That's far too much a restriction compare to the little misplacement due to precision we have today. Frankly I just don't want to see this in dt OR only if an option. But this would complicate further the code I suppose!

**Comment by TurboGit** [comment]
> The lens distortions in Lensfun lib are 5th or 7th order polynomials in 2D, they are not invertible in general. So that goal will always meet a dead-end, it will be at best inaccurate,

Fully agree, but I still prefer that than having to redo all my masking if I change some distortion in my image.

**Comment by parafin** [comment]
> > One may expect that if you draw a circle and then distort the image, then the circle will get distorted too (e.g. become an ellipse). That is quite reasonable expectation too, which will get broken by your approach and should work with current.
> 
> To achieve this goal, then you move the distortion modules up the pipe, after your masks.

This is not a goal, that’s just about user expectations and consistency of software. I’m not sure if you’re just pretending not to understand this point to drive your argument by saying there are no alternatives to your viewpoint. That’s not productive.

> That's how it is in any raster image processing software. darktable abides by the same layering logic : modules = operations = layers, and order of operations in the pipe dictates the order of settings. Its surprising that we are still getting dead-set on a non-destructive mindset when the features we are discussing here are clearly raster-based internally and call for the same logic as Gimp or Photoshop.

Maybe that’s because darktable is a non-destructive raw editor, don’t you think? I don’t quite see how having raster effects relates to destructiveness of the workflow. darktable already has some raster functions, but still works, doesn’t it?

> 
> I mean, nobody objects here that changing exposure early in the pipe might void your parametric luma masking later in the pipe. You are all very comfortable with that. Why is it that drawn masks should abide by another logic, to tolerate second thoughts and clumsy workflows at the expense of accuracy and proper behaviour ? Painting should be a flawless and organic experience.

You’re concerned about accuracy of drawing, while discarding accuracy of selected pixels staying the same after changes to distortion modules. One may choose any of these options to call “proper behaviour”. So it has to be some compromise and discussion, not “my way or no way”.

> 
> You can try all you want to stick masks to RAW coordinates : it's doomed to fail. The lens distortions in Lensfun lib are 5th or 7th order polynomials in 2D, they are not invertible in general. So that goal will always meet a dead-end, it will be at best inaccurate, with inaccuracy getting worse as screen resolutions increase. Therefore that constraint should be lifted. There is only madness in trying to cope with impossible constraints that, by the way, are entirely made-up.

So again, I may have missed your point, because you are still being quite vague about how you want masks to work exactly (instead continuing to describe how current approach is flawed). You said that in your workflow circle will get transposed to correct position after distortion is changed in the pipeline. Isn’t it the same exact problem of backtransforming the coordinates of circle center and radius to original image coordinates and then back again? Please think through these use-cases before proclaiming that your idea surely works, because it may turn up that it will have the same inherent flaws as current design.

**Comment by TurboGit** [comment]
BTW, I don't see an issue with lens. I have added 2 shapes circle & brush (exposure +3EV to be visible) on a corner of a picture with a focal of 12 mm, here is the screen shot:

![image](https://user-images.githubusercontent.com/467069/114504167-bbe97500-9c2e-11eb-9b5a-1d8516094699.png)

I have then activated the lens correction:

![image](https://user-images.githubusercontent.com/467069/114504294-f226f480-9c2e-11eb-8ec9-4434c9c5f7fb.png)

As you can see part of the image on the corner is now not visible as the distortion correction is strong at 12mm, but the shapes and the masks are still at the proper location.

Then in lens correction I have set the scale to 0.8 to have bigger distortion.

![image](https://user-images.githubusercontent.com/467069/114504583-5f3a8a00-9c2f-11eb-87b0-14c2cd393582.png)

Again as you can see the shapes and masks have been moved a lot this time but they are still at the proper location.

All those screen-shot are at 100%/ I would certainly not say broken and for doing photography retouch this is a pretty good precision.

**Comment by TurboGit** [comment]
I have also tested placing a shape with the lens correction as in my last screenshot. It was correctly placed and when disabling the lens correction module the shapes and masks where at the proper position.

**Comment by elstoc** [comment]
> That's far too much a restriction compare to the little misplacement due to precision we have today. Frankly I just don't want to see this in dt OR only if an option. But this would complicate further the code I suppose!

I think you misunderstand me. I wasn't suggesting a change to the code but a change to user workflow to achieve what @aurelienpierre wants with the existing code.

Assuming that the user's (@aurelienpierre's) goal is "when I draw a circle I want the mask to be the same shape as the on-screen image and I'm willing to change my workflow to work around any limitations in this approach", there are two ways to do this. One is just a workflow change, the other is a workflow and code change. Both impose workflow limitations **if you want to achieve that goal**

- **workflow change only**: The only way to draw a circle on the image and have it remain a circle is to limit yourself to only drawing masks when distortions are switched off. Yes, the mask will be distorted when you switch distortions on again, but you were drawing those masks for a reason - to fix the image in some way - and if the fix was achieved on the undistorted image (I successfully brightened the eyes), imposing the distortion shouldn't change the nature of that fix (the mask still covers the same pixels). The limitation is that if you come back to those masks later, they will no longer be circular (for example). You can make them circular again by temporarily disabling distortions while editing. This makes editing easier and more predictable.
- **workflow and code change**: Change the co-ordinate system so that it's fixed after the distortions in the pipe. A circle will always be a circle but subsequently changing the distorting modules might change its position, size, orientation. The workflow limitation here is much more restrictive because you really can't change the distortions later without having to revisit all of your masks. Sometimes the change will be subtle and will be missed by the user (because you've changed the distortion and adversely impacted something - the mask - that you maybe did some time ago). At least with the previous approach the problems are obvious because they're issues with what you're doing now and there's a known way to correct them.

All said I prefer the first (current) scenario and in most cases I don't need this convoluted workflow to achieve what I want. I know that a circle won't always be a circle but I can use trial and error to achieve what I want and, in extremis, disable the distorting modules while I place my mask. Some combination of the two approaches (points on the raw, shapes on the distorted image) will probably have some of the limitations of both approaches. For example, if you define the centre of a circle with respect to the raw but it's radius with respect to the distorted image, changing the distortions will still change the shape, because the altered distortion might amend the calculated size (if the image has been distorted asymmetrically, in which direction do you measure the size?).

**Comment by TurboGit** [comment]
@elstoc : I was responding to Aurélien and I do fully agree with all you, @parafin and @AlicVB  said.

> You do see that the circle changed shape though, which is the "problem" we're discussing?

Ok, probably because it is not an issue to me :) The only valid goal here is to ensure (as you said) that whatever distortion the selected pixels for the shape is exactly the same. Another way to put that : a shape is created once and will always enclose the same set of pixels. All other scenario are broken if you ask me. So I'm still confused by what Aurélien is proposing, I can't believe such breakage seems preferable to anyone.

**Comment by aurelienpierre** [comment]
1. Who draws masks before the lens and perspective corrections are applied ? I really don't get it. First step of any image editing is to normalize the image, colors and distortions. You don't put your film under the enlarger before the revealing bath, I don't see why digital should allow all sort of silly behaviours.
2. Digital painting should behave like real-life painting. Round brushes produce round strokes. Period. What we do here is anamorphic drawing, letting users draw on the viewport plane while they actually draw on a geodesic shape that will be projected onto that plane later. 
3. If you want precise pixel masking, you use an arbitrary path. If you require a particular geometric shape, you expect a geometric shape. Circles are customarily used to add vignetting, if I'm expecting a round vignette in image, I don't want to hear excuses about why I'm served an ellipse instead. 
4. Many operations simply don't make sense in RAW geodesic space, where vertical lines are neither vertical nor lines. A linear gradient, for once.

My proposal is to have an option in mask manager to bypass all the `distort_transform` and `distort_backtransform` functions, because :

1. They are slow as hell,
2. Distortion modules can be moved up the pipe to distort everything below at a later stage (again, that's what you do in any raster editor) without having to care globally, in the pipe, about coordinates mapping (which, again, is not invertible anyway in general),
3. We can have a button to convert mask nodes coordinates depending on current distortions upon user request (just run the `distort_backtransform` on masks before changing distortion to record coordinates in RAW geodesic space, then run `distort_transform` on the after distortion is applied to get new coordinates in viewport planar space),
4. Sampling healing spots on non-corrected images makes no sense at all and is practically unusable, if you need to correct vertical or horizontal edges you will have close to no properly orientated edge as candidates for the source sampling,
5. Pushing/pulling matter in liquify also makes no sense before the distortion corrections, especially since, again, the vector shifts are defined in viewport space (and I bet it is why we often end up with self-crossing pathes),
6. Backtransforms are brittle by nature and will never be accurate. Do things accurately or don't bother doing them at all.
6. It opens the possibility to squeeze a raster drawing framework in dt in the future.

**Comment by AlicVB** [comment]
First, I'm very uneasy in that sort of "heated" discussions, esp. when I've strong positions and even more in english as I'm far to master the exact effect and meanings of my words... So please apologize if I offend anyone : that's not the goal !

To be clear : I (and I know that I'm not alone here) am opposed to have a "fence" between distort module that would move at the start of the pipe and others iop. Why : 
- simply because that would completely break my workflow : I heavily use maks *and* I heavily use distortions as creative tasks (so at the end of the workflow, once I'm done with all "technical" things) nothing fancy here : some special crop, little more rotation, emphasis some deformations, finally remove lens distortion correction to have curved horizon, add frame, etc... And even, very often, I have multiple versions of the same image with different "distortions"
All this tasks can definitively not be done as first steps in the workflow (at least I'm not able to do them...)
- because dt is not a raster editor. neither we can compare it to other softs. and one of it's key feature is that the order in which you use modules doesn't change the order of the pipe... that doesn't mean some order are not more efficient, that just mean that users can change their mind, refine things, etc...

but in fact, what is exactly the problems here : 
1. a circle can be not round.
2. there's no way to know what will be the result when you move the mouse on screen to put a circle

Both points are true.
1. the first one is just a matter of terminology : just call it "spot" or whatever, and maybe even change the icon. Yes, that will state clearly that dt doesn't have the feature "I want a true circle" and one time, when a user will be upset enough by this lack, he may code something like : instead of center+radius, use a "near-enough" set of point to define the circumference, transform them in initial image space, and save them as it... That will be slower, but he will have a "real" circle (until he add some other distortions)
2. this one can be solved more "simply" and that would be a great addition : the shape drawn under the mouse can be put through all the transformation routines, like we do for the ones that are "in place". that way, you will see the exact form you will obtain when you put it. The drawback here is the speed... I've no idea what would be the cost... (we doesn't need to be as accurate as the "definitive" form, though)

When we are at it, some remark on @aurelienpierre last post (he's faster than me to write english) : 
- there's always some compromise to accept. let's take a different example : we all agree to loose a very little precision (we call it acceptable) in favor to avoid an algo that would take 10s. on each pass. Now the key is what to call acceptable and what to call unacceptable... and here we don't agree (sadly)
- again, dt is not a raster editor. I don't agree with the "raster-module" naming. imho that's doesn't make sens at all. every action, ... are vectorial, scalable, ...
- I'm far from a specialist here, so you may explain it to me : in term of image quality, I would put all the distortions at the end of the pipe, so all the complex algo we have act directly on "real" pixels, not extrapolated ones... (taht doesn't mean I require that sort of pipe order, it's just by curiosity)

**Comment by parafin** [comment]
> 4. We can have a button to convert mask nodes coordinates depending on current distortions upon user request (just run the `distort_backtransform` on masks before changing distortion to record coordinates in RAW geodesic space, then run `distort_transform` on the after distortion is applied to get new coordinates in viewport planar space),

That part sounds to me a bit icky. Why not do it automatically? And again - you are saying backtransforms aren't precise, so here we're just ignoring that?

Also - how would mask re-usage work if you place it in different parts of pipe (before and after distortion modules)? They will just mismatch?

Otherwise I get what you're saying, but I suspect any re-implementation of masks will have a lot of bugs, rough edges and corner cases at first too. This stuff is messy.

**Comment by aurelienpierre** [comment]
Here I simulated the distortion of a Sigma 15-30 mm on top of the Nikon D800, through Lensfun (the module has a "distort" mode, so apprently, there is already some sort of backtransform built-in):
![sigma-15-30mm-nikond800](https://user-images.githubusercontent.com/2779157/114581622-2676d100-9c80-11eb-816c-d0bc55f505c3.jpg)

If I open this image in dt and try to clone stamp it with the good old module, I get a nearly perfect match (which would indicate the module does a central symmetry inside):
![Screenshot_20210413_174507](https://user-images.githubusercontent.com/2779157/114581807-51612500-9c80-11eb-9b1b-68641595717c.png)

Now, if I enable the lens correction with the exact same Lensfun profile (but in "correct" mode), I get the proper grid but a large mismatch):
![Screenshot_20210413_174756](https://user-images.githubusercontent.com/2779157/114582033-853c4a80-9c80-11eb-91c9-a5e7b55d1699.png)

This is what I get with exactly the same settings, with a version of dt where the `module->distort_transform` and `backtransform` are commented out (no fancy-pants coordinates corrections): 
![Screenshot_20210413_175520](https://user-images.githubusercontent.com/2779157/114583119-8e79e700-9c81-11eb-8917-694aa51e30e5.png)

Then, I simulate arbitrary perspective deformation:
![perspective](https://user-images.githubusercontent.com/2779157/114583641-1b24a500-9c82-11eb-9e40-0d0bfaf1f7df.jpg)

The perspective correction tool automatically reverts it fairly (squares are still a bit rectangular, but the grid is restored). However, it's nearly impossible to connect the grid properly with the spot tool:
![Screenshot_20210413_180345](https://user-images.githubusercontent.com/2779157/114584267-c9304f00-9c82-11eb-8505-566a897ef6da.png)

Again, disabling the `distort()` makes it a piece of cake : 
![Screenshot_20210413_180745](https://user-images.githubusercontent.com/2779157/114584741-3c39c580-9c83-11eb-8eda-493b4aa4266b.png)

Actually, I have spent the last 8 years thinking that's how it was done because it didn't make sense for me to manage coordinates at a global level in the pipeline. But I experienced many glitches without being to make sense of them. Without @ralfbrown comment below, I would never have guessed that pixels where always sampled in RAW space.

I don't know what else needs to be done to prove you that this design is monkey business (regardless if there are bugs, or if it affects masks or spots, it's the same logic around the same design and if all modules show the same misbehaviour, I doubt they are all bugged individually…).

**Comment by jenshannoschwalm** [comment]
> I'm far from a specialist here, so you may explain it to me : in term of image quality, I would put all the distortions at the end of the pipe, so all the complex algo we have act directly on "real" pixels, not extrapolated ones... (taht doesn't mean I require that sort of pipe order, it's just by curiosity)

I fully agree here (i know it's not the main topic here). The interpolation algo might introduce overshoots like lancozs3 and the later processing module might react on those artefacts the same way as on hight-frequ content.

**Comment by aurelienpierre** [comment]
> simply because that would completely break my workflow : I heavily use maks and I heavily use distortions as creative tasks (so at the end of the workflow, once I'm done with all "technical" things) nothing fancy here : some special crop, little more rotation, emphasis some deformations, finally remove lens distortion correction to have curved horizon, add frame, etc... And even, very often, I have multiple versions of the same image with different "distortions"
All this tasks can definitively not be done as first steps in the workflow (at least I'm not able to do them...)

What is preventing you from doing them early ? That's just methodology.

> because dt is not a raster editor. neither we can compare it to other softs. and one of it's key feature is that the order in which you use modules doesn't change the order of the pipe... that doesn't mean some order are not more efficient, that just mean that users can change their mind, refine things, etc...

darktable is a non-destructive editor with lots of pixel-based operations, so it has raster parts and borrows to raster logic a lot more than the usual non-destructive pipeline. And the very fact that order of settings does not change the order of the pipe is responsible for misleading users who carefully mess around the pipeline in random order, just because they can. It is a sequential pipeline, order matter. When you use parametric masks, you filter the input of the module where it sits in the pipe, changes lower in the pipe will void the parameters, that's how it is. Modules are filters aka layers, in darktable.

> the first one is just a matter of terminology : just call it "spot" or whatever, and maybe even change the icon. Yes, that will state clearly that dt doesn't have the feature "I want a true circle" and one time, when a user will be upset enough by this lack, he may code something like : instead of center+radius, use a "near-enough" set of point to define the circumference, transform them in initial image space, and save them as it... That will be slower, but he will have a "real" circle (until he add some other distortions)

That's like selling tomatoes in a jar saying "pickles" and, when customer complains about tomatoes not being pickles, just changing the label. No sir, I'm buying pickles because I need pickles, please deliver them or close your shop.

> far from a specialist here, so you may explain it to me : in term of image quality, I would put all the distortions at the end of the pipe, so all the complex algo we have act directly on "real" pixels, not extrapolated ones... (taht doesn't mean I require that sort of pipe order, it's just by curiosity)

Distortions modules are already movable in pipeline. So, if you stop tracking coordinates at a global pipeline level, only deal with whatever you get at module input, you get a GUI behaviour that matches the pipeline behaviour more closely. If you absolutely need to deal with distortions at the last stage of your workflow, moving distortions module last will give you the expected behaviour without making painting miserable.

> Also - how would mask re-usage work if you place it in different parts of pipe (before and after distortion modules)? They will just mismatch?

There are no mask before distortions modules right now, so all mask will see the same geometry. That's easy to handle by enforcing all masks are either after or before all distortion. Only geeks have decided it was a requirement to handle distortions and masks interleaving, users don't need that from a functional standpoint.

**Comment by aurelienpierre** [comment]
> I fully agree here (i know it's not the main topic here). The interpolation algo might introduce overshoots like lancozs3 and the later processing module might react on those artefacts the same way as on hight-frequ content.

If you are clumsy enough to paint over non-corrected geometry, I'm sure you don't care about interpolation aliasing artifacts.

**Comment by TurboGit** [comment]
> Now, if I enable the lens correction with the exact same Lensfun profile (but in "correct" mode), I get the proper grid but a large mismatch):

Looks like a bug where the source area is not transformed maybe.

**Comment by TurboGit** [comment]
@aurelienpierre : can you give me access your simulated distorted grid?

**Comment by aurelienpierre** [comment]
> Otherwise I get what you're saying, but I suspect any re-implementation of masks will have a lot of bugs, rough edges and corner cases at first too. This stuff is messy.

Nobody said re-implement. From my tests above, it's 2 lines of code to bypass in `dev/develop.c`, aka 2 checks to add.

**Comment by AlicVB** [comment]
> That's like selling tomatoes in a jar saying "pickles" and, when customer complains about tomatoes not being pickles, just changing the label. No sir, I'm buying pickles because I need pickles, please deliver them or close your shop.

"Dear customer, I'm really sorry to say that we don't sell pickles because we don't have any provider for that product at the moment. But we can sell you lot of other merchandises, like tomatoes, onions, or that new magic product that can imitate almost all the tastes, but takes more time to prepare and cook" :-D

**Comment by aurelienpierre** [comment]
@TurboGit the source images are posted in my comment.

**Comment by TurboGit** [comment]
@aurelienpierre : the image is 1000 x 563 far too small for real test and will indeed exhibit larger errors.

**Comment by elstoc** [comment]
> What is preventing you from doing them early ? That's just methodology

Some of these distortions are creative in nature and saying that you can only do them at the start of the process is a big assumption about people's workflow. It's not "just methodology". 

Personally, I have trouble visualising my desired end result from the raw and there's a lot of experimentation involved before I get an image I'm happy with - you obviously have a strong impression of how you want the image to look before you start and are able to work in a more methodical way to achieve your end result. But I can't say, right at the start of the process, that I know what distorting modules I will want. Very often the last thing I do on an image is to adjust the keystone/perspective creation or slightly alter crop or rotation (or even switch off lens correction because I find I prefer the effect without). I do not want these activities to mess with my prior masked adjustments.

**Comment by ralfbrown** [comment]
I believe that the mismatch Aurelien showed in the lens distortion example is due to the source and destination patches being distorted differently.  The current implementation applies the coordinate transforms to determine the area to be copied, but then does a simple blit (understandable, as it's much faster than trying to figure out where each individual pixel needs to be copied from).

**Comment by Mark-64** [comment]
Coming back to the original scope of the thread, I would move modules like lowpass and highpass after filmic.
To me they are mostly used for creative purposes, in combination with Lab blending modes (for example lowpass + softlight to create a glamour glow / soft contrats look), and those modes don't work well in the scene referred part of pipe.
Same for lut 3D, which I use with luts downloaded from various sources, in order to give a specific look to the image. That requires the module to be after filmic.

Just my two cents

**Comment by aurelienpierre** [comment]
#8675 shows why we can't move spots and retouch before perspective and lens correction modules.

**Comment by aurelienpierre** [comment]
> To me they are mostly used for creative purposes, in combination with Lab blending modes (for example lowpass + softlight to create a glamour glow / soft contrats look), and those modes don't work well in the scene referred part of pipe.

Soft contrast -> use bloom module.

For the lowpass/highpass… they are frequency filters, as the name suggests, and after filmic your gradients have been completely messed-up, especially provided that they work in Lab, which already will mess up gradients. Lab expects middle-grey at 18% (linear), so if you anchored grey in exposure first, that should be ok. Do you have precise cases where they don't work ?

(Not to mention… blooming effect should happen in RGB linear, the censorize module lets you do that in multiply blending mode).

> Same for lut 3D, which I use with luts downloaded from various sources, in order to give a specific look to the image. That requires the module to be after filmic.

Most definitely not. Generic LUT expect either linear, gamma or log encoded RGB. So you may use them in linear or gamma internally, or use unbreak color profile to convert linear RGB to log RGB, but they can't be after filmic. Of course, if you use ad-hoc LUT, you do what the provider says.

**Comment by aurelienpierre** [comment]
> Some of these distortions are creative in nature and saying that you can only do them at the start of the process is a big assumption about people's workflow. It's not "just methodology".

It most definitely is. Technical stuff goes first in pipeline. Creative stuff goes last. Why ? Because corrective editing is particular to each image, while creative stuff, if applied on normalized data, is transferable, scriptable, database-able. Nothing prevents you from apply distortions later in the pipe, or even to have a first instance of corrective distortion, and a second creative instance later in the pipe after your color edit. Sure, the interpolation and stuff will be less good than if done early, but eh, that's what workflows are for. And when I say "workflow", I don't mean the collection of random habits people take over time, I'm talking about a process that has been pondered carefully.

I really think darktable is guilty of having enforced a false feeling of freedom and enabling all kinds of careless behaviours just because it made them possible while not being really mandatory. The first thing you learn when you do Gimp or Photoshop or Krita is you better be sure your low layers are what you really want before stacking new stuff on them, because you won't be able to change them later. Image processing are all about layers, that's how you paint, that's how you blend and compose, it's a layered process where the last stages inherits the consequences of earlier decisions, whether you like it or not, or think it's possible otherwise or not (yes, it's possible : see how much it over-constrains the pipe and pisses edge-cases as if there were no tomorrow).

What's sneaky with dt is it uses a layering logic, but hides it under the non-destructive BS. It's still layers, all the more since modules can be re-ordered.

**Comment by elstoc** [comment]
> Nothing prevents you from applying distortions later in the pipe, or even to have a first instance of corrective distortion, and a second creative instance later in the pipe after your color edit

darktable won't let me duplicate crop/rotate, perspective correction or lens correction.

**Comment by aurelienpierre** [comment]
> darktable won't let me duplicate crop/rotate, perspective correction or lens correction and places limitations on where I'm permitted to move them.

Because they were meant for correction, but that's one `IOP_FLAGS_ONE_INSTANCE` to remove in the code.

**Comment by flannelhead** [comment]
Another possible change: moving `overexposed` before `colorout`? Previous discussion here: https://github.com/darktable-org/darktable/pull/8051

**Comment by spaceChRiS** [comment]
I know I am not in any way qualified to intervene, but the masks topic is too interesting. I wonder if the following could work as a compromise/achieve all goals:

1. Every mask element (stroke, circle etc.) is bound to the current point in history.
1. The shapes and coordinates for drawing the masks are bound to image coordinates at the current state (based on pipe order and history). Changing earlier distortions would move/change the shapes, but while drawing a circle is a circle.
1. When I add a new circle later in history, after applying/changing some additional distortions, coordinates and shapes are based on the new situation, meaning a circle is a circle when drawing, even if older circles show another shape now.

Main drawback would be that the history stack cannot be arbitrarily compressed anymore, because the distortions at time of drawing are applied to each mask shape. All distorting modules would have to stay with each entry in the history and could only be compressed in between two mask references.

Another drawback would be that non-circular circles can exist when distortions are changed later. However, this is already the case, therefore it may be more consistent to the user when distortions to masks are applied based on history and pipe rather than pipe only.

Do I miss something?

**Comment by Mark-64** [comment]
> Do you have precise cases where they don't work ?

Lut 3D before filmic (default), free landscape LUT taken from ON1 site (see the highlights clipped)

![DSC06211_02](https://user-images.githubusercontent.com/43290988/114770842-31a72b00-9d6c-11eb-8cf5-692b1df2a125.jpg)

Same LUT, after filmic

![DSC06211_01](https://user-images.githubusercontent.com/43290988/114770933-4be10900-9d6c-11eb-92b0-be94271d095e.jpg)

Lowpass with "softlight" blend mode, before filmic  (see the highlights clipped)

![_5290185_02](https://user-images.githubusercontent.com/43290988/114771117-7e8b0180-9d6c-11eb-9f40-71dc1553f618.jpg)

Module moved after filmic

![_5290185_03](https://user-images.githubusercontent.com/43290988/114771187-91053b00-9d6c-11eb-95a4-9c780721c3e6.jpg)

Those modules simply can't manage unbounded RGB values.

**Comment by spaceChRiS** [comment]
Hm, thinking about the masks more, I found that "my" solution would require backtransforms as well, to delta map between the different history states. Sorry for the noise. But it would simply be too good to have a solution where I can draw a straight horizon line while, at the same time, can add distortions later without sampling different pixels or moving/distorting masks/shapes.

**Comment by MStraeten** [comment]
> Those modules simply can't manage unbounded RGB values.
that depends on the LUT:
There are LUTs to reconvert image from a log image recording --> these needs to be before filmic
And there are plenty of LUTs around to apply a look in the display referred part of the pipe.
So there's no right or wrong position in the pipe - it's just a prioritization.
If darktable was lightroom then it would be in the display referred part of the pipe because millions of flies can't be wrong ;)

**Comment by aurelienpierre** [comment]
> Those modules simply can't manage unbounded RGB values.

I think you are confusing 2 things here:
1. bounded spaces,
2. linear spaces.

Filmic relies on the hypothesis that it gets unbounded and linear-ish light at input. It outputs log-gamma-encoded + S-contrast stuff that makes linear light look pretty on screen.

LUTs are by nature bounded. **But** they most definitely don't expect what filmic is cooking at its output, as I said they expect either pure linear, pure gamma or pure log RGB, but certainly not the mix of stuff filmic does. The proper way to use LUTs, in this context would be to move the exposure compensation after them, so the signal is still linear (or gamma) **but** bounded in [0; 1]. when the LUT is applied, then you move the general exposure up or down as requested, and finish with filmic if necessary.

Regarding the output of lowpass/highpass with unbounded values, actually it's rather the blending modes that can't manage them.  So, you have the choice between highpass/lowpass being inaccurate (or at least not being what they pretend to be - watch out edge artifacts) in the display-referred part of the pipe, vs. blending modes not being able to handle them in the scene-referred part.

That sounds irreconcilable but you have much better tools to apply sharpness or local tonemapping than lowpass and highpass.

**Comment by Mark-64** [comment]
> There are LUTs to reconvert image from a log image recording --> these needs to be before filmic
> And there are plenty of LUTs around to apply a look in the display referred part of the pipe.

I agree, but the first type is mostly for video, while photography is mostly about the second type

> The proper way to use LUTs, in this context would be to move the exposure compensation after them, so the signal is still linear (or gamma) **but** bounded in [0; 1]. when the LUT is applied, then you move the general exposure up or down as requested, and finish with filmic if necessary.

I tried, but lut 3D must be after input color profile, which in turn requires to move exposure after input color profile, and that is not recommended.
Or, in alternative, to use a second exposure module after lut 3D
Too much hassle and results do not look better.
I actually believe that most "artistic" luts around are designed for being used by programs with display referred workflow.

> That sounds irreconcilable but you have much better tools to apply sharpness or local tonemapping than lowpass and highpass.

Agree, but since lowpass/highpass are there and their main use case is together with Lab blending modes which don't work with unbounded space, I still believe their default place should be after filmic.
Not a big deal of course, we can always move them.

**Comment by aurelienpierre** [comment]
> I tried, but lut 3D must be after input color profile, which in turn requires to move exposure after input color profile, and that is not recommended.

Not recommended by whom ? Exposure is a safe module, you can move it wherever you want. You can perfectly use a first instance before input color profile/LUT to ensure RGB uses the whole [0; 1] range (better with LUTs, but only if you have true whites in there), apply LUTs, then finish brightening if needed to anchor middle grey with another instance of exposure.

>  I actually believe that most "artistic" luts around are designed for being used by programs with display referred workflow.

Which means pure gamma (power function) in bounded space. Not S curve and arbitrary adjustments on top. Applyings LUTs after creative edits gives you zero predictability over the result. Styles, scripts, shortcuts, LUT, etc. all need a normalized file at input, meaning WB corrected, and same color space as the one in which the LUT was created.

**Comment by RawConvert** [comment]
I read much of the above and whilst I don't understand it all, a possible way for dt to work occurred to me.  It's probably flawed!, but what would be wrong with this:
The pipeline has 3 distinct phases. First it does non-geometric edits - exposure, tones, colours, contrast and non-geo lens corrections like vignetting.  Then phase 2 covers geometric changes e.g. crop, rotate, lens, perspective.  Then finally there is re-sizing (which is part of the output process only?).
If you open or change a module which is part of phase 1, you would see the whole raw and no geo changes would be shown.  However as always you could zoom in, and perhaps there could be a new key command to zoom in to approximate a crop in phase 2.
Perhaps there would be a new key command to toggle between the image as at the end of phase 1 (no geo changes shown), and the final image at the end of all edits.
If you're looking at phase 1 then open or change a module in phase 2, the display will change to the final image.
If you're in phase 2 then open or change a module in phase 1, the display will change to the end of phase 1.
And as now, you could re-order the modules at your own risk.
Making the phase 1 changes on the whole image perhaps minimises certain boundary condition issues which are pertinent to "small" crops.
Also it sounds like some mask complications might be done away with.

**Comment by TurboGit** [comment]
Moving this for 3.8 at this stage.
