### ISSUE TITLE
Inconsistent rendering of images and layouts when switching between layouts

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#8882]
I would like to report a few graphical bugs that are most likely related to each other:

**Issue A:**
1. Enter lighttable view, go to culling (fixed) mode, click on any picture of your collection (but NOT the first picture).
2. Remove any selection (Ctrl-Shift-A)
3. Go to culling (dynamic) mode
-> You get the grey screen
4. Return to culling (fixed) mode
5. you are set to the first picture of your collection and the screen remains grey until you click on another picture.

**Expected behavior**
Since you did not make any picture selection, you should not be returned to the first picture of your collection but to the picture that was in focus before entering dynamic mode. Also, the screen should not be grey.

**Issue B:**
1. Remove any selection (Ctrl-Shift-A)
2. Enter lighttable view, go to culling (fixed) mode, click on the FIRST image in your collection to focus it.
3. Go to culling (dynamic) mode
-> You get a display "no image selected" but you still see the first picture from your collection 

**Expected behavior:** 
You should see a grey screen, since you have no pictures selected.
To get the grey screen, you need to perform the same steps, but in step number 1 DO NOT select the first image in your collection (pick any other image).
-> You get a display "no image selected !" on a grey background and the first image from fixed mode is not rendered anymore.

**Issue C:**
1. Select one or more pictures
2. Enter culling (dynamic) mode
3. Open a different collection while in dynamic mode
-> You still see the pictures of the previous collection.

**Expected behavior:** 
Since you have no pictures selected in the new collection, the screen should be rerendered to grey when loading a different collection.

**Issue D:**
1. Select one or more pictures
2. Enter culling (dynamic) mode
3. Open darkroom
4. Return to lighttable
-> you are once more in lighttable culling (dynamic) but the filmstrip in the bottom has been replaced by the time line that is normally only visible in filemanager layout.

**Issue E:** (similar to D)
1. Select one or more pictures
2. Enter culling (dynamic) mode
3. Enter full preview layout
4. Press Escape to leave full preview 
-> you are not returned to lighttable culling (dynamic) but to some weird layout that looks like a broken filemanager layout. Also, the filmstrip in the bottom has been replaced by the time line that is normally only visible in filemanager layout.
![image](https://user-images.githubusercontent.com/2805109/117364393-2607d980-aebe-11eb-947c-5b4dc4712083.png)

**Which commit introduced the error**
Not sure. I think this has been around for long.

**Platform**
* darktable version : 3.5.0+1967~g4024d7d73
* OS                : Manjaro Linux
* OpenCL installed  : yes
* OpenCL activated  :  yes

**Comment by AlicVB** [comment]
Sorry for the delay, I've seen this then forgot it...
So : 
- issue A : more a feature request. the behavior you describe is "normal" as we have no way to know what were the previous images...
- issue B : I've reproduce once, but then I can't anymore... there's certainly other steps involved (apart if the below PR has fixed it)
- issue C : the below PR should fix it
- issues D & E : should be fixed in PR #8989 (stupid forgetting from when we have added the bottom icons)

**Comment by Solarer** [comment]
Can confirm that PR #8989 fixes C,D and E. A and B are still present.

I need to explain A better, it is not only a feature request. Even if we don't remember our original position and are returned to the first image in our collection, the screen should not stay grey until I scroll to the next picture. Instead, the first image of the collection should be displayed right away. The screen does not refresh automatically.

B: Has unfortunately not been fixed by above PR. You need to enter culling (fixed) mode without a selection. That is the important step, sorry I wrote it in wrong order

**Comment by Solarer** [comment]
@TurboGit can you open once more? You closed it as I was typing :D

**Comment by TurboGit** [comment]
> @TurboGit can you open once more? You closed it as I was typing :D

Just a little note that it got closed automatically when I merged the PR.

**Comment by AlicVB** [comment]
@Solarer : go it (I think) PR #8997 should fix it
Thanks for your detailed tests and report !

**Comment by Solarer** [comment]
Yes, has been fixed by the PR. 
Thank you for the fast action!
